version: "2"
run:
  tests: true
linters:
  enable:
    - errname
    - errorlint
    - exhaustive
    - gocritic
    - misspell
    - nolintlint
    - revive
    - unconvert
    - unparam
  settings:
    gocritic:
      enabled-tags:
        - diagnostic
        - style
        - performance
    revive:
      rules:
        - name: exported
          disabled: false
  exclusions:
    generated: lax
    rules:
      - path: (.+)\.go$
        text: should have a package comment
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
