.PHONY: help build dev test lint lint-fix git-hooks frontend-dev types

# Variables
DATA_DIR=./data
PORT?=8080
LOG_LEVEL?=info

help:
	@echo "mddb - Markdown Document & Database System"
	@echo ""
	@echo "Available targets:"
	@echo "  make build          - Build Go server (auto-generates frontend)"
	@echo "  make dev            - Run the server in development mode"
	@echo "  make test           - Run backend tests"
	@echo "  make types          - Generate TypeScript types from Go structs"
	@echo "  make lint           - Run linters (Go + frontend)"
	@echo "  make lint-fix       - Fix all linting issues automatically"
	@echo "  make git-hooks      - Install git pre-commit hooks"
	@echo "  make frontend-dev   - Run frontend dev server (http://localhost:5173)"
	@echo ""
	@echo "Environment variables:"
	@echo "  PORT=8080           - Server port (default: 8080)"
	@echo "  LOG_LEVEL=info      - Log level (debug|info|warn|error)"

# Build frontend and Go server
build: types
	go generate ./...
	go install ./cmd/...

types:
	go run github.com/gzuidhof/tygo@latest generate
	@echo "// Code generated by tygo. DO NOT EDIT." > frontend/src/types.ts
	@cat frontend/src/models.gen.ts | grep -v "Code generated by tygo" | grep -v "source:" >> frontend/src/types.ts
	@cat frontend/src/storage.gen.ts | grep -v "Code generated by tygo" | grep -v "source:" >> frontend/src/types.ts
	@cat frontend/src/handlers.gen.ts | grep -v "Code generated by tygo" | grep -v "source:" >> frontend/src/types.ts
	@echo "" >> frontend/src/types.ts
	@rm frontend/src/models.gen.ts frontend/src/storage.gen.ts frontend/src/handlers.gen.ts

dev: build
	mddb -port $(PORT) -data-dir $(DATA_DIR) -log-level $(LOG_LEVEL)

test:
	go test -cover ./...

lint:
	@which golangci-lint > /dev/null || (echo "Installing golangci-lint..." && go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest)
	golangci-lint run ./...
	cd frontend && pnpm lint

lint-fix:
	golangci-lint run ./... --fix || true
	cd frontend && pnpm lint:fix

git-hooks:
	@echo "Installing git pre-commit hooks..."
	@mkdir -p .git/hooks
	@cp ./scripts/pre-commit .git/hooks/pre-commit
	@chmod +x .git/hooks/pre-commit
	@echo "✓ Git hooks installed"

frontend-dev:
	cd frontend && pnpm install && pnpm dev
