name: 'MDDB Setup Action'
description: 'Shared setup steps for MDDB'
runs:
  using: "composite"
  steps:
    - name: Set Environment Variables
      run: |
        echo "CGO_ENABLED=0" >> "$GITHUB_ENV"
      shell: bash
    - uses: actions/setup-go@v6
      with:
        go-version-file: go.mod
    - uses: actions/setup-python@v6
      with:
        python-version: '3.x'
    - uses: pnpm/action-setup@v4
      with:
        version: 10
    - uses: actions/setup-node@v6
      with:
        node-version: "24"
        cache: pnpm
        cache-dependency-path: pnpm-lock.yaml
    - name: Configure Python for Windows
      run: |
        $pythonPath = (Get-Command python).Source
        $pythonDir = Split-Path $pythonPath
        $python3Path = Join-Path $pythonDir "python3.exe"
        if (!(Test-Path $python3Path)) {
          New-Item -ItemType HardLink -Path $python3Path -Value $pythonPath
          Write-Host "Created python3.exe hardlink"
        }
        & pnpm config set python "$pythonPath"
        Write-Host "Configured pnpm python to $pythonPath"
      if: runner.os == 'Windows'
      shell: pwsh
