// SDK generation specification for mddb HTTP routes.
package dto

import (
	"reflect"

	"github.com/maruel/apisdkgen/apispec"
)

// SDKAPI returns the API surface generated for mddb clients and documentation.
func SDKAPI() apispec.Config[ErrorCode] {
	return apispec.Config[ErrorCode]{
		ClientScopes: []apispec.ClientScope{
			{Name: "org", PathPrefix: "/api/v1/organizations/{orgID}", Parameter: "orgID"},
			{Name: "ws", PathPrefix: "/api/v1/workspaces/{wsID}", Parameter: "wsID"},
		},
		Routes: []apispec.Route{
			{Name: "getHealth", Method: "GET", Path: "/api/v1/health", Resp: reflect.TypeFor[HealthResponse]()},
			{Name: "getServerDetail", Method: "GET", Path: "/api/v1/admin/server", Resp: reflect.TypeFor[AdminServerDetail]()},
			{Name: "getConfig", Method: "GET", Path: "/api/v1/server/config", Resp: reflect.TypeFor[ServerConfigResponse]()},
			{Name: "updateConfig", Method: "POST", Path: "/api/v1/server/config", Req: reflect.TypeFor[UpdateServerConfigRequest](), Resp: reflect.TypeFor[UpdateServerConfigResponse]()},
			{Name: "login", Method: "POST", Path: "/api/v1/auth/login", Req: reflect.TypeFor[LoginRequest](), Resp: reflect.TypeFor[AuthResponse]()},
			{Name: "register", Method: "POST", Path: "/api/v1/auth/register", Req: reflect.TypeFor[RegisterRequest](), Resp: reflect.TypeFor[AuthResponse]()},
			{Name: "acceptOrgInvitation", Method: "POST", Path: "/api/v1/auth/invitations/org/accept", Req: reflect.TypeFor[AcceptInvitationRequest](), Resp: reflect.TypeFor[AuthResponse]()},
			{Name: "acceptWSInvitation", Method: "POST", Path: "/api/v1/auth/invitations/ws/accept", Req: reflect.TypeFor[AcceptInvitationRequest](), Resp: reflect.TypeFor[AuthResponse]()},
			{Name: "listProviders", Method: "GET", Path: "/api/v1/auth/providers", Resp: reflect.TypeFor[ProvidersResponse]()},
			{Name: "getMe", Method: "GET", Path: "/api/v1/auth/me", Resp: reflect.TypeFor[UserResponse]()},
			{Name: "logout", Method: "POST", Path: "/api/v1/auth/logout", Resp: reflect.TypeFor[LogoutResponse]()},
			{Name: "listSessions", Method: "GET", Path: "/api/v1/auth/sessions", Resp: reflect.TypeFor[ListSessionsResponse]()},
			{Name: "revokeSession", Method: "POST", Path: "/api/v1/auth/sessions/revoke", Req: reflect.TypeFor[RevokeSessionRequest](), Resp: reflect.TypeFor[RevokeSessionResponse]()},
			{Name: "revokeAllSessions", Method: "POST", Path: "/api/v1/auth/sessions/revoke-all", Resp: reflect.TypeFor[RevokeAllSessionsResponse]()},
			{Name: "changeEmail", Method: "POST", Path: "/api/v1/auth/email", Req: reflect.TypeFor[ChangeEmailRequest](), Resp: reflect.TypeFor[ChangeEmailResponse]()},
			{Name: "sendVerificationEmail", Method: "POST", Path: "/api/v1/auth/email/send-verification", Resp: reflect.TypeFor[SendVerificationEmailResponse]()},
			{Name: "switchWorkspace", Method: "POST", Path: "/api/v1/auth/switch-workspace", Req: reflect.TypeFor[SwitchWorkspaceRequest](), Resp: reflect.TypeFor[SwitchWorkspaceResponse]()},
			{Name: "updateUserSettings", Method: "POST", Path: "/api/v1/auth/settings", Req: reflect.TypeFor[UpdateUserSettingsRequest](), Resp: reflect.TypeFor[UserResponse]()},
			{Name: "setPassword", Method: "POST", Path: "/api/v1/auth/password", Req: reflect.TypeFor[SetPasswordRequest](), Resp: reflect.TypeFor[OkResponse]()},
			{Name: "linkOAuth", Method: "POST", Path: "/api/v1/auth/oauth/link", Req: reflect.TypeFor[LinkOAuthAccountRequest](), Resp: reflect.TypeFor[LinkOAuthAccountResponse]()},
			{Name: "unlinkOAuth", Method: "POST", Path: "/api/v1/auth/oauth/unlink", Req: reflect.TypeFor[UnlinkOAuthAccountRequest](), Resp: reflect.TypeFor[UnlinkOAuthAccountResponse]()},
			{Name: "createOrganization", Method: "POST", Path: "/api/v1/organizations", Req: reflect.TypeFor[CreateOrganizationRequest](), Resp: reflect.TypeFor[OrganizationResponse]()},
			{Name: "getOrganization", Method: "GET", Path: "/api/v1/organizations/{orgID}", Resp: reflect.TypeFor[OrganizationResponse]()},
			{Name: "updateOrganization", Method: "POST", Path: "/api/v1/organizations/{orgID}", Req: reflect.TypeFor[UpdateOrganizationRequest](), Resp: reflect.TypeFor[OrganizationResponse]()},
			{Name: "updateOrgPreferences", Method: "POST", Path: "/api/v1/organizations/{orgID}/settings", Req: reflect.TypeFor[UpdateOrgPreferencesRequest](), Resp: reflect.TypeFor[OrganizationResponse]()},
			{Name: "listUsers", Method: "GET", Path: "/api/v1/organizations/{orgID}/users", Resp: reflect.TypeFor[ListUsersResponse]()},
			{Name: "updateOrgMemberRole", Method: "POST", Path: "/api/v1/organizations/{orgID}/users/role", Req: reflect.TypeFor[UpdateOrgMemberRoleRequest](), Resp: reflect.TypeFor[UserResponse]()},
			{Name: "removeOrgMember", Method: "POST", Path: "/api/v1/organizations/{orgID}/users/remove", Req: reflect.TypeFor[RemoveOrgMemberRequest](), Resp: reflect.TypeFor[OkResponse]()},
			{Name: "listOrgInvitations", Method: "GET", Path: "/api/v1/organizations/{orgID}/invitations", Resp: reflect.TypeFor[ListOrgInvitationsResponse]()},
			{Name: "createOrgInvitation", Method: "POST", Path: "/api/v1/organizations/{orgID}/invitations", Req: reflect.TypeFor[CreateOrgInvitationRequest](), Resp: reflect.TypeFor[OrgInvitationResponse]()},
			{Name: "createWorkspace", Method: "POST", Path: "/api/v1/organizations/{orgID}/workspaces", Req: reflect.TypeFor[CreateWorkspaceRequest](), Resp: reflect.TypeFor[WorkspaceResponse]()},
			{Name: "startImport", Method: "POST", Path: "/api/v1/organizations/{orgID}/notion/import", Req: reflect.TypeFor[NotionImportRequest](), Resp: reflect.TypeFor[NotionImportResponse]()},
			{Name: "getStatus", Method: "GET", Path: "/api/v1/organizations/{orgID}/notion/import/{importWsID}/status", Resp: reflect.TypeFor[NotionImportStatusResponse]()},
			{Name: "getWorkspace", Method: "GET", Path: "/api/v1/workspaces/{wsID}", Resp: reflect.TypeFor[WorkspaceResponse]()},
			{Name: "updateWorkspace", Method: "POST", Path: "/api/v1/workspaces/{wsID}", Req: reflect.TypeFor[UpdateWorkspaceRequest](), Resp: reflect.TypeFor[WorkspaceResponse]()},
			{Name: "updateWSMembershipSettings", Method: "POST", Path: "/api/v1/workspaces/{wsID}/settings/membership", Req: reflect.TypeFor[UpdateWSMembershipSettingsRequest](), Resp: reflect.TypeFor[WSMembershipResponse]()},
			{Name: "getGitRemote", Method: "GET", Path: "/api/v1/workspaces/{wsID}/settings/git", Resp: reflect.TypeFor[GitRemoteResponse]()},
			{Name: "updateGitRemote", Method: "POST", Path: "/api/v1/workspaces/{wsID}/settings/git", Req: reflect.TypeFor[UpdateGitRemoteRequest](), Resp: reflect.TypeFor[GitRemoteResponse]()},
			{Name: "pushGit", Method: "POST", Path: "/api/v1/workspaces/{wsID}/settings/git/push", Resp: reflect.TypeFor[OkResponse]()},
			{Name: "pullGit", Method: "POST", Path: "/api/v1/workspaces/{wsID}/settings/git/pull", Resp: reflect.TypeFor[OkResponse]()},
			{Name: "getSyncStatus", Method: "GET", Path: "/api/v1/workspaces/{wsID}/settings/git/status", Resp: reflect.TypeFor[GitSyncStatusResponse]()},
			{Name: "setupGitHubAppRemote", Method: "POST", Path: "/api/v1/workspaces/{wsID}/settings/git/github-app", Req: reflect.TypeFor[SetupGitHubAppRemoteRequest](), Resp: reflect.TypeFor[GitRemoteResponse]()},
			{Name: "deleteGitRemote", Method: "POST", Path: "/api/v1/workspaces/{wsID}/settings/git/delete", Resp: reflect.TypeFor[OkResponse]()},
			{Name: "listGitHubAppRepos", Method: "POST", Path: "/api/v1/github-app/repos", Req: reflect.TypeFor[ListGitHubAppReposRequest](), Resp: reflect.TypeFor[ListGitHubAppReposResponse]()},
			{Name: "listGitHubAppInstallations", Method: "GET", Path: "/api/v1/github-app/installations", Resp: reflect.TypeFor[ListGitHubAppInstallationsResponse]()},
			{Name: "isGitHubAppAvailable", Method: "GET", Path: "/api/v1/github-app/available", Resp: reflect.TypeFor[GitHubAppAvailableResponse]()},
			{Name: "cancelImport", Method: "POST", Path: "/api/v1/workspaces/{wsID}/notion/import/cancel", Resp: reflect.TypeFor[NotionImportCancelResponse]()},
			{Name: "listWorkspaceMembers", Method: "GET", Path: "/api/v1/workspaces/{wsID}/members", Resp: reflect.TypeFor[ListWorkspaceMembersResponse]()},
			{Name: "resolveUsers", Method: "POST", Path: "/api/v1/workspaces/{wsID}/users/resolve", Req: reflect.TypeFor[ResolveUsersRequest](), Resp: reflect.TypeFor[ResolveUsersResponse]()},
			{Name: "updateWSMemberRole", Method: "POST", Path: "/api/v1/workspaces/{wsID}/users/role", Req: reflect.TypeFor[UpdateWSMemberRoleRequest](), Resp: reflect.TypeFor[UserResponse]()},
			{Name: "listWSInvitations", Method: "GET", Path: "/api/v1/workspaces/{wsID}/invitations", Resp: reflect.TypeFor[ListWSInvitationsResponse]()},
			{Name: "createWSInvitation", Method: "POST", Path: "/api/v1/workspaces/{wsID}/invitations", Req: reflect.TypeFor[CreateWSInvitationRequest](), Resp: reflect.TypeFor[WSInvitationResponse]()},
			{Name: "getNodeTitles", Method: "GET", Path: "/api/v1/workspaces/{wsID}/nodes/titles", Req: reflect.TypeFor[GetNodeTitlesRequest](), QueryFromReq: true, QueryParams: []string{"ids"}, Resp: reflect.TypeFor[GetNodeTitlesResponse]()},
			{Name: "getNode", Method: "GET", Path: "/api/v1/workspaces/{wsID}/nodes/{id}", Resp: reflect.TypeFor[NodeResponse]()},
			{Name: "listNodeChildren", Method: "GET", Path: "/api/v1/workspaces/{wsID}/nodes/{id}/children", Resp: reflect.TypeFor[ListNodeChildrenResponse]()},
			{Name: "moveNode", Method: "POST", Path: "/api/v1/workspaces/{wsID}/nodes/{id}/move", Req: reflect.TypeFor[MoveNodeRequest](), Resp: reflect.TypeFor[MoveNodeResponse]()},
			{Name: "deleteNode", Method: "POST", Path: "/api/v1/workspaces/{wsID}/nodes/{id}/delete", Resp: reflect.TypeFor[DeleteNodeResponse]()},
			{Name: "createPage", Method: "POST", Path: "/api/v1/workspaces/{wsID}/nodes/{id}/page/create", Req: reflect.TypeFor[CreatePageRequest](), Resp: reflect.TypeFor[CreatePageResponse]()},
			{Name: "getPage", Method: "GET", Path: "/api/v1/workspaces/{wsID}/nodes/{id}/page", Resp: reflect.TypeFor[GetPageResponse]()},
			{Name: "updatePage", Method: "POST", Path: "/api/v1/workspaces/{wsID}/nodes/{id}/page", Req: reflect.TypeFor[UpdatePageRequest](), Resp: reflect.TypeFor[UpdatePageResponse]()},
			{Name: "deletePage", Method: "POST", Path: "/api/v1/workspaces/{wsID}/nodes/{id}/page/delete", Resp: reflect.TypeFor[DeletePageResponse]()},
			{Name: "updatePageFrontmatter", Method: "POST", Path: "/api/v1/workspaces/{wsID}/nodes/{id}/page/frontmatter", Req: reflect.TypeFor[UpdatePageFrontmatterRequest](), Resp: reflect.TypeFor[UpdatePageFrontmatterResponse]()},
			{Name: "createTable", Method: "POST", Path: "/api/v1/workspaces/{wsID}/nodes/{id}/table/create", Req: reflect.TypeFor[CreateTableRequest](), Resp: reflect.TypeFor[CreateTableUnderParentResponse]()},
			{Name: "getTable", Method: "GET", Path: "/api/v1/workspaces/{wsID}/nodes/{id}/table", Resp: reflect.TypeFor[GetTableSchemaResponse]()},
			{Name: "updateTable", Method: "POST", Path: "/api/v1/workspaces/{wsID}/nodes/{id}/table", Req: reflect.TypeFor[UpdateTableRequest](), Resp: reflect.TypeFor[UpdateTableResponse]()},
			{Name: "deleteTable", Method: "POST", Path: "/api/v1/workspaces/{wsID}/nodes/{id}/table/delete", Resp: reflect.TypeFor[DeleteTableResponse]()},
			{Name: "createView", Method: "POST", Path: "/api/v1/workspaces/{wsID}/nodes/{id}/views/create", Req: reflect.TypeFor[CreateViewRequest](), Resp: reflect.TypeFor[CreateViewResponse]()},
			{Name: "updateView", Method: "POST", Path: "/api/v1/workspaces/{wsID}/nodes/{id}/views/{viewID}", Req: reflect.TypeFor[UpdateViewRequest](), Resp: reflect.TypeFor[UpdateViewResponse]()},
			{Name: "deleteView", Method: "POST", Path: "/api/v1/workspaces/{wsID}/nodes/{id}/views/{viewID}/delete", Resp: reflect.TypeFor[DeleteViewResponse]()},
			{Name: "listRecords", Method: "GET", Path: "/api/v1/workspaces/{wsID}/nodes/{id}/table/records", Req: reflect.TypeFor[ListRecordsRequest](), QueryFromReq: true, QueryParams: []string{"view_id", "filters", "sorts", "offset", "limit"}, Resp: reflect.TypeFor[ListRecordsResponse]()},
			{Name: "getRecord", Method: "GET", Path: "/api/v1/workspaces/{wsID}/nodes/{id}/table/records/{rid}", Resp: reflect.TypeFor[GetRecordResponse]()},
			{Name: "createRecord", Method: "POST", Path: "/api/v1/workspaces/{wsID}/nodes/{id}/table/records/create", Req: reflect.TypeFor[CreateRecordRequest](), Resp: reflect.TypeFor[CreateRecordResponse]()},
			{Name: "updateRecord", Method: "POST", Path: "/api/v1/workspaces/{wsID}/nodes/{id}/table/records/{rid}", Req: reflect.TypeFor[UpdateRecordRequest](), Resp: reflect.TypeFor[UpdateRecordResponse]()},
			{Name: "deleteRecord", Method: "POST", Path: "/api/v1/workspaces/{wsID}/nodes/{id}/table/records/{rid}/delete", Resp: reflect.TypeFor[DeleteRecordResponse]()},
			{Name: "listNodeVersions", Method: "GET", Path: "/api/v1/workspaces/{wsID}/nodes/{id}/history", Req: reflect.TypeFor[ListNodeVersionsRequest](), QueryFromReq: true, QueryParams: []string{"limit"}, Resp: reflect.TypeFor[ListNodeVersionsResponse]()},
			{Name: "getNodeVersion", Method: "GET", Path: "/api/v1/workspaces/{wsID}/nodes/{id}/history/{hash}", Resp: reflect.TypeFor[GetNodeVersionResponse]()},
			{Name: "listNodeAssets", Method: "GET", Path: "/api/v1/workspaces/{wsID}/nodes/{id}/assets", Resp: reflect.TypeFor[ListNodeAssetsResponse]()},
			{Name: "deleteNodeAsset", Method: "POST", Path: "/api/v1/workspaces/{wsID}/nodes/{id}/assets/{name}/delete", Resp: reflect.TypeFor[DeleteNodeAssetResponse]()},
			{Name: "search", Method: "POST", Path: "/api/v1/workspaces/{wsID}/search", Req: reflect.TypeFor[SearchRequest](), Resp: reflect.TypeFor[SearchResponse]()},
			{Name: "listNotifications", Method: "GET", Path: "/api/v1/notifications", Req: reflect.TypeFor[ListNotificationsRequest](), QueryFromReq: true, QueryParams: []string{"limit", "offset", "unread_only"}, Resp: reflect.TypeFor[ListNotificationsResponse]()},
			{Name: "getUnreadCount", Method: "GET", Path: "/api/v1/notifications/unread-count", Resp: reflect.TypeFor[UnreadCountResponse]()},
			{Name: "markNotificationRead", Method: "POST", Path: "/api/v1/notifications/{id}/read", Resp: reflect.TypeFor[MarkNotificationReadResponse]()},
			{Name: "markAllNotificationsRead", Method: "POST", Path: "/api/v1/notifications/read-all", Resp: reflect.TypeFor[MarkAllNotificationsReadResponse]()},
			{Name: "deleteNotification", Method: "POST", Path: "/api/v1/notifications/{id}/delete", Resp: reflect.TypeFor[DeleteNotificationResponse]()},
			{Name: "getNotificationPrefs", Method: "GET", Path: "/api/v1/notifications/preferences", Resp: reflect.TypeFor[NotificationPrefsDTO]()},
			{Name: "updateNotificationPrefs", Method: "POST", Path: "/api/v1/notifications/preferences", Req: reflect.TypeFor[UpdateNotificationPrefsRequest](), Resp: reflect.TypeFor[NotificationPrefsDTO]()},
			{Name: "getVAPIDPublicKey", Method: "GET", Path: "/api/v1/notifications/vapid-key", Resp: reflect.TypeFor[VAPIDKeyResponse]()},
			{Name: "subscribePush", Method: "POST", Path: "/api/v1/notifications/subscribe", Req: reflect.TypeFor[PushSubscribeRequest](), Resp: reflect.TypeFor[PushSubscribeResponse]()},
			{Name: "unsubscribePush", Method: "POST", Path: "/api/v1/notifications/unsubscribe", Req: reflect.TypeFor[PushUnsubscribeRequest](), Resp: reflect.TypeFor[PushUnsubscribeResponse]()},
		},
		SDKPackagePaths: map[string]struct{}{reflect.TypeFor[ErrorResponse]().PkgPath(): {}},
		ExtraSeeds:      []reflect.Type{reflect.TypeFor[ErrorResponse]()},
		SpecialTypes: []apispec.SpecialType{
			{Type: reflect.TypeFor[any](), TSType: "unknown", KTType: "JsonElement", SwiftType: "JSONValue", DocType: "JSONValue", TSValidate: "%[1]s"},
		},
		APIDocTitle: "mddb API Reference",
		APIDocIntro: "RESTful JSON API for mddb at `/api/v1/`.",
	}
}
