name: 'MDDB Test Action'
description: 'Shared test steps for MDDB'
inputs:
  codecov-token:
    description: 'Token for Codecov'
    required: false

runs:
  using: "composite"
  steps:
    - name: Lint (Go)
      if: runner.os == 'Linux'
      uses: golangci/golangci-lint-action@v9
    - name: Lint (Frontend)
      if: runner.os == 'Linux'
      run: make lint-frontend
      shell: bash
    - name: Lint (Binaries)
      if: runner.os == 'Linux'
      run: make lint-binaries
      shell: bash
    - run: make build
      shell: bash
    - name: Test
      if: runner.os != 'Linux'
      run: make test
      shell: bash
    - name: Coverage
      if: runner.os == 'Linux'
      run: make coverage
      shell: bash
    - name: Upload Coverage
      if: runner.os == 'Linux'
      uses: codecov/codecov-action@v5
      with:
        token: ${{ inputs.codecov-token }}
        files: coverage.out,coverage/lcov.info
    - run: make e2e
      shell: bash
    - uses: actions/upload-artifact@v4
      id: playwright-report
      if: always()
      with:
        name: playwright-report-${{ runner.os }}
        path: playwright-report/
        retention-days: 7
    - name: Playwright Report Summary
      if: always()
      run: |
        if [ -f playwright-report/results.json ]; then
          PASSED=$(jq '.stats.expected' playwright-report/results.json)
          FAILED=$(jq '.stats.unexpected' playwright-report/results.json)
          SKIPPED=$(jq '.stats.skipped' playwright-report/results.json)
          FLAKY=$(jq '.stats.flaky' playwright-report/results.json)
          TOTAL=$((PASSED + FAILED + SKIPPED + FLAKY))
          {
            echo "## Playwright Test Results (${{ runner.os }})"
            echo ""
            if [ "$FAILED" -gt 0 ]; then
              echo "| Status | Count |"
              echo "|--------|-------|"
              echo "| :white_check_mark: Passed | $PASSED |"
              echo "| :x: Failed | $FAILED |"
              [ "$FLAKY" -gt 0 ] && echo "| :warning: Flaky | $FLAKY |"
              [ "$SKIPPED" -gt 0 ] && echo "| :fast_forward: Skipped | $SKIPPED |"
              echo ""
            else
              echo ":white_check_mark: **All $TOTAL tests passed on ${{ runner.os }}**"
            fi
            echo ""
            echo ":page_facing_up: Playwright report for ${{ runner.os }} is available as a workflow artifact."
          } >> "$GITHUB_STEP_SUMMARY"
        fi
      shell: bash
