// Code generated by apiclient. DO NOT EDIT.

import type {
  AcceptInvitationRequest,
  AdminOrgsResponse,
  AdminStatsResponse,
  AdminUsersResponse,
  AuthResponse,
  CreateInvitationRequest,
  CreateNodeRequest,
  CreateOrganizationRequest,
  CreatePageRequest,
  CreatePageResponse,
  CreateRecordRequest,
  CreateRecordResponse,
  CreateTableRequest,
  CreateTableResponse,
  DeletePageAssetResponse,
  DeletePageResponse,
  DeleteRecordResponse,
  DeleteTableResponse,
  ErrorResponse,
  GetPageResponse,
  GetPageVersionResponse,
  GetRecordResponse,
  GetTableResponse,
  GitRemoteResponse,
  HealthResponse,
  InvitationResponse,
  ListInvitationsResponse,
  ListNodesResponse,
  ListPageAssetsResponse,
  ListPageVersionsRequest,
  ListPageVersionsResponse,
  ListPagesResponse,
  ListRecordsRequest,
  ListRecordsResponse,
  ListTablesResponse,
  ListUsersResponse,
  LoginRequest,
  MembershipResponse,
  NodeResponse,
  OkResponse,
  OrganizationResponse,
  RegisterRequest,
  SearchRequest,
  SearchResponse,
  SwitchOrgRequest,
  SwitchOrgResponse,
  UpdateGitRemoteRequest,
  UpdateMembershipSettingsRequest,
  UpdateOrgPreferencesRequest,
  UpdateOrganizationRequest,
  UpdatePageRequest,
  UpdatePageResponse,
  UpdateRecordRequest,
  UpdateRecordResponse,
  UpdateTableRequest,
  UpdateTableResponse,
  UpdateUserRoleRequest,
  UpdateUserSettingsRequest,
  UserResponse,
} from './types.gen';

/** Fetch function type - implement to add auth headers */
export type FetchFn = (url: string, init?: RequestInit) => Promise<Response>;

/** API error with parsed error response */
export class APIError extends Error {
  constructor(
    public status: number,
    public response: ErrorResponse
  ) {
    super(response.error.message);
    this.name = 'APIError';
  }
}

async function get<T>(fetchFn: FetchFn, url: string): Promise<T> {
  const res = await fetchFn(url);
  if (!res.ok) {
    const error = (await res.json()) as ErrorResponse;
    throw new APIError(res.status, error);
  }
  return res.json() as Promise<T>;
}

async function post<T>(fetchFn: FetchFn, url: string, body?: object): Promise<T> {
  const init: RequestInit = { method: 'POST' };
  if (body) {
    init.headers = { 'Content-Type': 'application/json' };
    init.body = JSON.stringify(body);
  }
  const res = await fetchFn(url, init);
  if (!res.ok) {
    const error = (await res.json()) as ErrorResponse;
    throw new APIError(res.status, error);
  }
  return res.json() as Promise<T>;
}

/** Creates a typed API client */
export function createAPIClient(fetchFn: FetchFn) {
  return {
    admin: {
      organizations: {
        list: () => get<AdminOrgsResponse>(fetchFn, `/api/admin/organizations`),
      },
      stats: {
        get: () => get<AdminStatsResponse>(fetchFn, `/api/admin/stats`),
      },
      users: {
        list: () => get<AdminUsersResponse>(fetchFn, `/api/admin/users`),
      },
    },
    auth: {
      invitations: {
        acceptInvitation: (options: AcceptInvitationRequest) => post<AuthResponse>(fetchFn, `/api/auth/invitations/accept`, options),
      },
      me: {
        get: () => get<UserResponse>(fetchFn, `/api/auth/me`),
      },
      settings: {
        update: (options: UpdateUserSettingsRequest) => post<UserResponse>(fetchFn, `/api/auth/settings`, options),
      },
      login: (options: LoginRequest) => post<AuthResponse>(fetchFn, `/api/auth/login`, options),
      register: (options: RegisterRequest) => post<AuthResponse>(fetchFn, `/api/auth/register`, options),
      switchOrg: (options: SwitchOrgRequest) => post<SwitchOrgResponse>(fetchFn, `/api/auth/switch-org`, options),
    },
    health: {
      get: () => get<HealthResponse>(fetchFn, `/api/health`),
    },
    organizations: {
      create: (options: CreateOrganizationRequest) => post<OrganizationResponse>(fetchFn, `/api/organizations`, options),
    },

    /** Returns an org-scoped API client */
    org(orgID: string) {
      return {
        invitations: {
          create: (options: CreateInvitationRequest) => post<InvitationResponse>(fetchFn, `/api/${orgID}/invitations`, options),
          list: () => get<ListInvitationsResponse>(fetchFn, `/api/${orgID}/invitations`),
        },
        nodes: {
          create: (options: CreateNodeRequest) => post<NodeResponse>(fetchFn, `/api/${orgID}/nodes`, options),
          get: (id: string) => get<NodeResponse>(fetchFn, `/api/${orgID}/nodes/${id}`),
          list: () => get<ListNodesResponse>(fetchFn, `/api/${orgID}/nodes`),
        },
        pages: {
          assets: {
            delete: (id: string, name: string) => post<DeletePageAssetResponse>(fetchFn, `/api/${orgID}/pages/${id}/assets/${name}/delete`),
            list: (id: string) => get<ListPageAssetsResponse>(fetchFn, `/api/${orgID}/pages/${id}/assets`),
          },
          history: {
            get: (id: string, hash: string) => get<GetPageVersionResponse>(fetchFn, `/api/${orgID}/pages/${id}/history/${hash}`),
            async list(id: string, options: ListPageVersionsRequest): Promise<ListPageVersionsResponse> {
              const params = new URLSearchParams();
              if (options.Limit) params.set('limit', String(options.Limit));
              const url = `/api/${orgID}/pages/${id}/history` + (params.toString() ? `?${params}` : '');
              return get<ListPageVersionsResponse>(fetchFn, url);
            },
          },
          create: (options: CreatePageRequest) => post<CreatePageResponse>(fetchFn, `/api/${orgID}/pages`, options),
          delete: (id: string) => post<DeletePageResponse>(fetchFn, `/api/${orgID}/pages/${id}/delete`),
          get: (id: string) => get<GetPageResponse>(fetchFn, `/api/${orgID}/pages/${id}`),
          list: () => get<ListPagesResponse>(fetchFn, `/api/${orgID}/pages`),
          update: (id: string, options: UpdatePageRequest) => post<UpdatePageResponse>(fetchFn, `/api/${orgID}/pages/${id}`, options),
        },
        settings: {
          git: {
            delete: () => post<OkResponse>(fetchFn, `/api/${orgID}/settings/git/delete`),
            get: () => get<GitRemoteResponse>(fetchFn, `/api/${orgID}/settings/git`),
            pushGit: () => post<OkResponse>(fetchFn, `/api/${orgID}/settings/git/push`),
            update: (options: UpdateGitRemoteRequest) => post<GitRemoteResponse>(fetchFn, `/api/${orgID}/settings/git`, options),
          },
          membership: {
            update: (options: UpdateMembershipSettingsRequest) => post<MembershipResponse>(fetchFn, `/api/${orgID}/settings/membership`, options),
          },
          organization: {
            get: () => get<OrganizationResponse>(fetchFn, `/api/${orgID}/settings/organization`),
            update: (options: UpdateOrganizationRequest) => post<OrganizationResponse>(fetchFn, `/api/${orgID}/settings/organization`, options),
          },
          preferences: {
            update: (options: UpdateOrgPreferencesRequest) => post<OrganizationResponse>(fetchFn, `/api/${orgID}/settings/preferences`, options),
          },
        },
        tables: {
          records: {
            create: (id: string, options: CreateRecordRequest) => post<CreateRecordResponse>(fetchFn, `/api/${orgID}/tables/${id}/records`, options),
            delete: (id: string, rid: string) => post<DeleteRecordResponse>(fetchFn, `/api/${orgID}/tables/${id}/records/${rid}/delete`),
            get: (id: string, rid: string) => get<GetRecordResponse>(fetchFn, `/api/${orgID}/tables/${id}/records/${rid}`),
            async list(id: string, options: ListRecordsRequest): Promise<ListRecordsResponse> {
              const params = new URLSearchParams();
              if (options.Offset) params.set('offset', String(options.Offset));
              if (options.Limit) params.set('limit', String(options.Limit));
              const url = `/api/${orgID}/tables/${id}/records` + (params.toString() ? `?${params}` : '');
              return get<ListRecordsResponse>(fetchFn, url);
            },
            update: (id: string, rid: string, options: UpdateRecordRequest) => post<UpdateRecordResponse>(fetchFn, `/api/${orgID}/tables/${id}/records/${rid}`, options),
          },
          create: (options: CreateTableRequest) => post<CreateTableResponse>(fetchFn, `/api/${orgID}/tables`, options),
          delete: (id: string) => post<DeleteTableResponse>(fetchFn, `/api/${orgID}/tables/${id}/delete`),
          get: (id: string) => get<GetTableResponse>(fetchFn, `/api/${orgID}/tables/${id}`),
          list: () => get<ListTablesResponse>(fetchFn, `/api/${orgID}/tables`),
          update: (id: string, options: UpdateTableRequest) => post<UpdateTableResponse>(fetchFn, `/api/${orgID}/tables/${id}`, options),
        },
        users: {
          role: {
            update: (options: UpdateUserRoleRequest) => post<UserResponse>(fetchFn, `/api/${orgID}/users/role`, options),
          },
          list: () => get<ListUsersResponse>(fetchFn, `/api/${orgID}/users`),
        },
        search: (options: SearchRequest) => post<SearchResponse>(fetchFn, `/api/${orgID}/search`, options),
      };
    },
  };
}

export type APIClient = ReturnType<typeof createAPIClient>;
export type OrgAPIClient = ReturnType<APIClient['org']>;
