// Code generated by apiclient. DO NOT EDIT.

import type {
  AcceptInvitationRequest,
  AdminOrgsResponse,
  AdminStatsResponse,
  AdminUsersResponse,
  AuthResponse,
  ChangeEmailRequest,
  ChangeEmailResponse,
  CreateOrgInvitationRequest,
  CreateOrganizationRequest,
  CreatePageRequest,
  CreatePageResponse,
  CreateRecordRequest,
  CreateRecordResponse,
  CreateTableRequest,
  CreateTableUnderParentResponse,
  CreateWSInvitationRequest,
  CreateWorkspaceRequest,
  DeleteNodeAssetResponse,
  DeleteNodeResponse,
  DeletePageResponse,
  DeleteRecordResponse,
  DeleteTableResponse,
  ErrorResponse,
  GetNodeVersionResponse,
  GetPageResponse,
  GetRecordResponse,
  GetTableSchemaResponse,
  GitRemoteResponse,
  HealthResponse,
  ListNodeAssetsResponse,
  ListNodeChildrenResponse,
  ListNodeVersionsRequest,
  ListNodeVersionsResponse,
  ListNodesResponse,
  ListOrgInvitationsResponse,
  ListRecordsRequest,
  ListRecordsResponse,
  ListSessionsResponse,
  ListUsersResponse,
  ListWSInvitationsResponse,
  LoginRequest,
  LogoutResponse,
  NodeResponse,
  OkResponse,
  OrgInvitationResponse,
  OrganizationResponse,
  ProvidersResponse,
  RegisterRequest,
  RevokeAllSessionsResponse,
  RevokeSessionRequest,
  RevokeSessionResponse,
  SearchRequest,
  SearchResponse,
  SwitchOrgRequest,
  SwitchOrgResponse,
  SwitchWorkspaceRequest,
  SwitchWorkspaceResponse,
  UpdateGitRemoteRequest,
  UpdateOrgMemberRoleRequest,
  UpdateOrgPreferencesRequest,
  UpdateOrganizationRequest,
  UpdatePageRequest,
  UpdatePageResponse,
  UpdateRecordRequest,
  UpdateRecordResponse,
  UpdateTableRequest,
  UpdateTableResponse,
  UpdateUserSettingsRequest,
  UpdateWSMemberRoleRequest,
  UpdateWSMembershipSettingsRequest,
  UpdateWorkspaceRequest,
  UserResponse,
  WSInvitationResponse,
  WSMembershipResponse,
  WorkspaceResponse,
} from './types.gen';

/** Fetch function type - implement to add auth headers */
export type FetchFn = (url: string, init?: RequestInit) => Promise<Response>;

/** API error with parsed error response */
export class APIError extends Error {
  constructor(
    public status: number,
    public response: ErrorResponse
  ) {
    super(response.error.message);
    this.name = 'APIError';
  }
}

async function get<T>(fetchFn: FetchFn, url: string): Promise<T> {
  const res = await fetchFn(url);
  if (!res.ok) {
    const error = (await res.json()) as ErrorResponse;
    throw new APIError(res.status, error);
  }
  return res.json() as Promise<T>;
}

async function post<T>(fetchFn: FetchFn, url: string, body?: object): Promise<T> {
  const init: RequestInit = { method: 'POST' };
  if (body) {
    init.headers = { 'Content-Type': 'application/json' };
    init.body = JSON.stringify(body);
  }
  const res = await fetchFn(url, init);
  if (!res.ok) {
    const error = (await res.json()) as ErrorResponse;
    throw new APIError(res.status, error);
  }
  return res.json() as Promise<T>;
}

/** Creates a typed API client */
export function createAPIClient(fetchFn: FetchFn) {
  return {
    admin: {
      organizations: {
        listAllOrgs: () => get<AdminOrgsResponse>(fetchFn, `/api/admin/organizations`),
      },
      getAdminStats: () => get<AdminStatsResponse>(fetchFn, `/api/admin/stats`),
      listAllUsers: () => get<AdminUsersResponse>(fetchFn, `/api/admin/users`),
    },
    auth: {
      invitations: {
        acceptOrgInvitation: (options: AcceptInvitationRequest) => post<AuthResponse>(fetchFn, `/api/auth/invitations/org/accept`, options),
        acceptWSInvitation: (options: AcceptInvitationRequest) => post<AuthResponse>(fetchFn, `/api/auth/invitations/ws/accept`, options),
      },
      sessions: {
        listSessions: () => get<ListSessionsResponse>(fetchFn, `/api/auth/sessions`),
        revokeAllSessions: () => post<RevokeAllSessionsResponse>(fetchFn, `/api/auth/sessions/revoke-all`),
        revokeSession: (options: RevokeSessionRequest) => post<RevokeSessionResponse>(fetchFn, `/api/auth/sessions/revoke`, options),
      },
      changeEmail: (options: ChangeEmailRequest) => post<ChangeEmailResponse>(fetchFn, `/api/auth/email`, options),
      getMe: () => get<UserResponse>(fetchFn, `/api/auth/me`),
      listProviders: () => get<ProvidersResponse>(fetchFn, `/api/auth/providers`),
      login: (options: LoginRequest) => post<AuthResponse>(fetchFn, `/api/auth/login`, options),
      logout: () => post<LogoutResponse>(fetchFn, `/api/auth/logout`),
      register: (options: RegisterRequest) => post<AuthResponse>(fetchFn, `/api/auth/register`, options),
      switchOrg: (options: SwitchOrgRequest) => post<SwitchOrgResponse>(fetchFn, `/api/auth/switch-org`, options),
      switchWorkspace: (options: SwitchWorkspaceRequest) => post<SwitchWorkspaceResponse>(fetchFn, `/api/auth/switch-workspace`, options),
      updateUserSettings: (options: UpdateUserSettingsRequest) => post<UserResponse>(fetchFn, `/api/auth/settings`, options),
    },
    organizations: {
      createOrganization: (options: CreateOrganizationRequest) => post<OrganizationResponse>(fetchFn, `/api/organizations`, options),
    },
    getHealth: () => get<HealthResponse>(fetchFn, `/api/health`),

    /** Returns an org-scoped API client */
    org(orgID: string) {
      return {
        invitations: {
          createOrgInvitation: (options: CreateOrgInvitationRequest) => post<OrgInvitationResponse>(fetchFn, `/api/organizations/${orgID}/invitations`, options),
          listOrgInvitations: () => get<ListOrgInvitationsResponse>(fetchFn, `/api/organizations/${orgID}/invitations`),
        },
        organizations: {
          getOrganization: () => get<OrganizationResponse>(fetchFn, `/api/organizations/${orgID}`),
          updateOrganization: (options: UpdateOrganizationRequest) => post<OrganizationResponse>(fetchFn, `/api/organizations/${orgID}`, options),
        },
        settings: {
          updateOrgPreferences: (options: UpdateOrgPreferencesRequest) => post<OrganizationResponse>(fetchFn, `/api/organizations/${orgID}/settings`, options),
        },
        users: {
          listUsers: () => get<ListUsersResponse>(fetchFn, `/api/organizations/${orgID}/users`),
          updateOrgMemberRole: (options: UpdateOrgMemberRoleRequest) => post<UserResponse>(fetchFn, `/api/organizations/${orgID}/users/role`, options),
        },
        workspaces: {
          createWorkspace: (options: CreateWorkspaceRequest) => post<WorkspaceResponse>(fetchFn, `/api/organizations/${orgID}/workspaces`, options),
        },
      };
    },

    /** Returns a workspace-scoped API client */
    ws(wsID: string) {
      return {
        invitations: {
          createWSInvitation: (options: CreateWSInvitationRequest) => post<WSInvitationResponse>(fetchFn, `/api/workspaces/${wsID}/invitations`, options),
          listWSInvitations: () => get<ListWSInvitationsResponse>(fetchFn, `/api/workspaces/${wsID}/invitations`),
        },
        nodes: {
          assets: {
            deleteNodeAsset: (id: string, name: string) => post<DeleteNodeAssetResponse>(fetchFn, `/api/workspaces/${wsID}/nodes/${id}/assets/${name}/delete`),
            listNodeAssets: (id: string) => get<ListNodeAssetsResponse>(fetchFn, `/api/workspaces/${wsID}/nodes/${id}/assets`),
          },
          history: {
            getNodeVersion: (id: string, hash: string) => get<GetNodeVersionResponse>(fetchFn, `/api/workspaces/${wsID}/nodes/${id}/history/${hash}`),
            async listNodeVersions(id: string, options: ListNodeVersionsRequest): Promise<ListNodeVersionsResponse> {
              const params = new URLSearchParams();
              if (options.Limit) params.set('limit', String(options.Limit));
              const url = `/api/workspaces/${wsID}/nodes/${id}/history` + (params.toString() ? `?${params}` : '');
              return get<ListNodeVersionsResponse>(fetchFn, url);
            },
          },
          page: {
            createPage: (id: string, options: CreatePageRequest) => post<CreatePageResponse>(fetchFn, `/api/workspaces/${wsID}/nodes/${id}/page/create`, options),
            deletePage: (id: string) => post<DeletePageResponse>(fetchFn, `/api/workspaces/${wsID}/nodes/${id}/page/delete`),
            getPage: (id: string) => get<GetPageResponse>(fetchFn, `/api/workspaces/${wsID}/nodes/${id}/page`),
            updatePage: (id: string, options: UpdatePageRequest) => post<UpdatePageResponse>(fetchFn, `/api/workspaces/${wsID}/nodes/${id}/page`, options),
          },
          table: {
            records: {
              createRecord: (id: string, options: CreateRecordRequest) => post<CreateRecordResponse>(fetchFn, `/api/workspaces/${wsID}/nodes/${id}/table/records/create`, options),
              deleteRecord: (id: string, rid: string) => post<DeleteRecordResponse>(fetchFn, `/api/workspaces/${wsID}/nodes/${id}/table/records/${rid}/delete`),
              getRecord: (id: string, rid: string) => get<GetRecordResponse>(fetchFn, `/api/workspaces/${wsID}/nodes/${id}/table/records/${rid}`),
              async listRecords(id: string, options: ListRecordsRequest): Promise<ListRecordsResponse> {
                const params = new URLSearchParams();
                if (options.Offset) params.set('offset', String(options.Offset));
                if (options.Limit) params.set('limit', String(options.Limit));
                const url = `/api/workspaces/${wsID}/nodes/${id}/table/records` + (params.toString() ? `?${params}` : '');
                return get<ListRecordsResponse>(fetchFn, url);
              },
              updateRecord: (id: string, rid: string, options: UpdateRecordRequest) => post<UpdateRecordResponse>(fetchFn, `/api/workspaces/${wsID}/nodes/${id}/table/records/${rid}`, options),
            },
            createTable: (id: string, options: CreateTableRequest) => post<CreateTableUnderParentResponse>(fetchFn, `/api/workspaces/${wsID}/nodes/${id}/table/create`, options),
            deleteTable: (id: string) => post<DeleteTableResponse>(fetchFn, `/api/workspaces/${wsID}/nodes/${id}/table/delete`),
            getTable: (id: string) => get<GetTableSchemaResponse>(fetchFn, `/api/workspaces/${wsID}/nodes/${id}/table`),
            updateTable: (id: string, options: UpdateTableRequest) => post<UpdateTableResponse>(fetchFn, `/api/workspaces/${wsID}/nodes/${id}/table`, options),
          },
          deleteNode: (id: string) => post<DeleteNodeResponse>(fetchFn, `/api/workspaces/${wsID}/nodes/${id}/delete`),
          getNode: (id: string) => get<NodeResponse>(fetchFn, `/api/workspaces/${wsID}/nodes/${id}`),
          listNodeChildren: (id: string) => get<ListNodeChildrenResponse>(fetchFn, `/api/workspaces/${wsID}/nodes/${id}/children`),
          listNodes: () => get<ListNodesResponse>(fetchFn, `/api/workspaces/${wsID}/nodes`),
        },
        settings: {
          git: {
            deleteGitRemote: () => post<OkResponse>(fetchFn, `/api/workspaces/${wsID}/settings/git/delete`),
            getGitRemote: () => get<GitRemoteResponse>(fetchFn, `/api/workspaces/${wsID}/settings/git`),
            pushGit: () => post<OkResponse>(fetchFn, `/api/workspaces/${wsID}/settings/git/push`),
            updateGitRemote: (options: UpdateGitRemoteRequest) => post<GitRemoteResponse>(fetchFn, `/api/workspaces/${wsID}/settings/git`, options),
          },
          updateWSMembershipSettings: (options: UpdateWSMembershipSettingsRequest) => post<WSMembershipResponse>(fetchFn, `/api/workspaces/${wsID}/settings/membership`, options),
        },
        users: {
          updateWSMemberRole: (options: UpdateWSMemberRoleRequest) => post<UserResponse>(fetchFn, `/api/workspaces/${wsID}/users/role`, options),
        },
        workspaces: {
          getWorkspace: () => get<WorkspaceResponse>(fetchFn, `/api/workspaces/${wsID}`),
          updateWorkspace: (options: UpdateWorkspaceRequest) => post<WorkspaceResponse>(fetchFn, `/api/workspaces/${wsID}`, options),
        },
        search: (options: SearchRequest) => post<SearchResponse>(fetchFn, `/api/workspaces/${wsID}/search`, options),
      };
    },
  };
}

export type APIClient = ReturnType<typeof createAPIClient>;
export type OrgAPIClient = ReturnType<APIClient['org']>;
export type WSAPIClient = ReturnType<APIClient['ws']>;
