// Code generated by tygo. DO NOT EDIT.

//////////

/**
 * LoginRequest is a request to log in.
 */
export interface LoginRequest {
  email: string;
  password: string;
}
/**
 * LoginResponse is a response from logging in.
 */
export interface LoginResponse {
  token: string;
  user?: User;
}
/**
 * RegisterRequest is a request to register a new user.
 */
export interface RegisterRequest {
  email: string;
  password: string;
  name: string;
}
/**
 * MeRequest is a request to get current user info.
 */
export interface MeRequest {
}
/**
 * ListPagesRequest is a request to list all pages.
 */
export interface ListPagesRequest {
  OrgID: string;
}
/**
 * ListPagesResponse is a response containing a list of pages.
 */
export interface ListPagesResponse {
  pages: any[];
}
/**
 * GetPageRequest is a request to get a page.
 */
export interface GetPageRequest {
  OrgID: string;
  ID: string;
}
/**
 * GetPageResponse is a response containing a page.
 */
export interface GetPageResponse {
  id: string;
  title: string;
  content: string;
}
/**
 * CreatePageRequest is a request to create a page.
 */
export interface CreatePageRequest {
  OrgID: string;
  title: string;
  content: string;
}
/**
 * CreatePageResponse is a response from creating a page.
 */
export interface CreatePageResponse {
  id: string;
}
/**
 * UpdatePageRequest is a request to update a page.
 */
export interface UpdatePageRequest {
  OrgID: string;
  ID: string;
  title: string;
  content: string;
}
/**
 * UpdatePageResponse is a response from updating a page.
 */
export interface UpdatePageResponse {
  id: string;
}
/**
 * DeletePageRequest is a request to delete a page.
 */
export interface DeletePageRequest {
  OrgID: string;
  ID: string;
}
/**
 * DeletePageResponse is a response from deleting a page.
 */
export interface DeletePageResponse {
}
/**
 * GetPageHistoryRequest is a request to get page history.
 */
export interface GetPageHistoryRequest {
  OrgID: string;
  ID: string;
}
/**
 * GetPageHistoryResponse is a response containing page history.
 */
export interface GetPageHistoryResponse {
  history: (Commit | undefined)[];
}
/**
 * GetPageVersionRequest is a request to get a specific page version.
 */
export interface GetPageVersionRequest {
  OrgID: string;
  ID: string;
  Hash: string;
}
/**
 * GetPageVersionResponse is a response containing page content at a version.
 */
export interface GetPageVersionResponse {
  content: string;
}
/**
 * ListDatabasesRequest is a request to list databases.
 */
export interface ListDatabasesRequest {
  OrgID: string;
}
/**
 * ListDatabasesResponse is a response containing a list of databases.
 */
export interface ListDatabasesResponse {
  databases: any[];
}
/**
 * GetDatabaseRequest is a request to get a database.
 */
export interface GetDatabaseRequest {
  OrgID: string;
  ID: string;
}
/**
 * GetDatabaseResponse is a response containing a database.
 */
export interface GetDatabaseResponse {
  id: string;
  title: string;
  columns: Column[];
  created: string;
  modified: string;
}
/**
 * CreateDatabaseRequest is a request to create a database.
 */
export interface CreateDatabaseRequest {
  OrgID: string;
  title: string;
  columns: Column[];
}
/**
 * CreateDatabaseResponse is a response from creating a database.
 */
export interface CreateDatabaseResponse {
  id: string;
}
/**
 * UpdateDatabaseRequest is a request to update a database.
 */
export interface UpdateDatabaseRequest {
  OrgID: string;
  ID: string;
  title: string;
  columns: Column[];
}
/**
 * UpdateDatabaseResponse is a response from updating a database.
 */
export interface UpdateDatabaseResponse {
  id: string;
}
/**
 * DeleteDatabaseRequest is a request to delete a database.
 */
export interface DeleteDatabaseRequest {
  OrgID: string;
  ID: string;
}
/**
 * DeleteDatabaseResponse is a response from deleting a database.
 */
export interface DeleteDatabaseResponse {
}
/**
 * ListRecordsRequest is a request to list records in a database.
 */
export interface ListRecordsRequest {
  OrgID: string;
  ID: string;
  Offset: number /* int */;
  Limit: number /* int */;
}
/**
 * ListRecordsResponse is a response containing a list of records.
 */
export interface ListRecordsResponse {
  records: { [key: string]: any}[];
}
/**
 * CreateRecordRequest is a request to create a record.
 */
export interface CreateRecordRequest {
  OrgID: string;
  ID: string;
  data: { [key: string]: any};
}
/**
 * CreateRecordResponse is a response from creating a record.
 */
export interface CreateRecordResponse {
  id: string;
}
/**
 * UpdateRecordRequest is a request to update a record.
 */
export interface UpdateRecordRequest {
  OrgID: string;
  ID: string;
  RID: string;
  data: { [key: string]: any};
}
/**
 * UpdateRecordResponse is a response from updating a record.
 */
export interface UpdateRecordResponse {
  id: string;
}
/**
 * GetRecordRequest is a request to get a record.
 */
export interface GetRecordRequest {
  OrgID: string;
  ID: string;
  RID: string;
}
/**
 * GetRecordResponse is a response containing a record.
 */
export interface GetRecordResponse {
  id: string;
  data: { [key: string]: any};
  created: string;
  modified: string;
}
/**
 * DeleteRecordRequest is a request to delete a record.
 */
export interface DeleteRecordRequest {
  OrgID: string;
  ID: string;
  RID: string;
}
/**
 * DeleteRecordResponse is a response from deleting a record.
 */
export interface DeleteRecordResponse {
}
/**
 * ListNodesRequest is a request to list nodes.
 */
export interface ListNodesRequest {
  OrgID: string;
}
/**
 * ListNodesResponse is a response containing a list of nodes.
 */
export interface ListNodesResponse {
  nodes: (Node | undefined)[];
}
/**
 * GetNodeRequest is a request to get a node.
 */
export interface GetNodeRequest {
  OrgID: string;
  ID: string;
}
/**
 * CreateNodeRequest is a request to create a node.
 */
export interface CreateNodeRequest {
  OrgID: string;
  parent_id?: string;
  title: string;
  type: NodeType;
}
/**
 * ListPageAssetsRequest is a request to list assets in a page.
 */
export interface ListPageAssetsRequest {
  OrgID: string;
  PageID: string;
}
/**
 * ListPageAssetsResponse is a response containing a list of assets.
 */
export interface ListPageAssetsResponse {
  assets: any[];
}
/**
 * UploadPageAssetRequest is a request to upload an asset to a page.
 */
export interface UploadPageAssetRequest {
  OrgID: string;
  PageID: string;
}
/**
 * UploadPageAssetResponse is a response from uploading an asset.
 */
export interface UploadPageAssetResponse {
  id: string;
  name: string;
  size: number /* int64 */;
  mime_type: string;
}
/**
 * DeletePageAssetRequest is a request to delete an asset from a page.
 */
export interface DeletePageAssetRequest {
  OrgID: string;
  PageID: string;
  AssetName: string;
}
/**
 * DeletePageAssetResponse is a response from deleting an asset.
 */
export interface DeletePageAssetResponse {
}
/**
 * ServeAssetRequest is a request to serve an asset file directly.
 */
export interface ServeAssetRequest {
  OrgID: string;
  PageID: string;
  AssetName: string;
}
/**
 * ServeAssetResponse wraps the binary asset data.
 */
export interface ServeAssetResponse {
  data: string;
  mime_type: string;
}
/**
 * SearchRequest is a request to search pages and databases
 */
export interface SearchRequest {
  OrgID: string;
  query: string;
  limit?: number /* int */;
  match_title?: boolean;
  match_body?: boolean;
  match_fields?: boolean;
}
/**
 * SearchResponse is the response to a search request
 */
export interface SearchResponse {
  results: SearchResult[];
}
/**
 * CreateInvitationRequest is a request to create an invitation.
 */
export interface CreateInvitationRequest {
  OrgID: string;
  email: string;
  role: UserRole;
}
/**
 * ListInvitationsRequest is a request to list invitations for an organization.
 */
export interface ListInvitationsRequest {
  OrgID: string;
}
/**
 * ListInvitationsResponse is a response containing a list of invitations.
 */
export interface ListInvitationsResponse {
  invitations: (Invitation | undefined)[];
}
/**
 * AcceptInvitationRequest is a request to accept an invitation.
 */
export interface AcceptInvitationRequest {
  token: string;
  password: string;
  name: string;
}
/**
 * SwitchOrgRequest is a request to switch active organization.
 */
export interface SwitchOrgRequest {
  org_id: string;
}
/**
 * SwitchOrgResponse is a response from switching organization.
 */
export interface SwitchOrgResponse {
  token: string;
  user?: User;
}
/**
 * UpdateMembershipSettingsRequest is a request to update user preferences within an organization.
 */
export interface UpdateMembershipSettingsRequest {
  OrgID: string;
  settings: MembershipSettings;
}
/**
 * UpdateOrgSettingsRequest is a request to update organization-wide settings.
 */
export interface UpdateOrgSettingsRequest {
  OrgID: string;
  settings: OrganizationSettings;
}
/**
 * HealthRequest is a request to check system health.
 */
export interface HealthRequest {
}
/**
 * HealthResponse is a response from a health check.
 */
export interface HealthResponse {
  status: string;
  version: string;
}
/**
 * ListUsersRequest is a request to list users.
 */
export interface ListUsersRequest {
  OrgID: string;
}
/**
 * UpdateRoleRequest is a request to update a user's role.
 */
export interface UpdateRoleRequest {
  OrgID: string;
  user_id: string;
  role: UserRole;
}
/**
 * ListUsersResponse is a response containing a list of users.
 */
export interface ListUsersResponse {
  users: (User | undefined)[];
}
/**
 * UpdateUserSettingsRequest is a request to update user global settings.
 */
export interface UpdateUserSettingsRequest {
  settings: UserSettings;
}

//////////
/*
Package models defines the core data structures used throughout the application.
*/

/**
 * Node represents the unified content entity (can be a Page, a Database, or both)
 */
export interface Node {
  id: string;
  parent_id?: string; // For hierarchical structure
  title: string;
  content?: string; // Markdown content (Page part)
  columns?: Column[]; // Schema (Database part)
  created: string;
  modified: string;
  tags?: string[];
  favicon_url?: string;
  type: NodeType; // document, database, or both
  children?: (Node | undefined)[]; // Nested nodes
}
/**
 * NodeType defines what features are enabled for a node
 */
/**
 * NodeTypeDocument represents a markdown document
 */
export const NodeTypeDocument = "document";
/**
 * NodeTypeDatabase represents a structured database
 */
export const NodeTypeDatabase = "database";
/**
 * NodeTypeHybrid represents an entity that is both a document and a database
 */
export const NodeTypeHybrid = "hybrid";
export type NodeType = typeof NodeTypeDocument | typeof NodeTypeDatabase | typeof NodeTypeHybrid;
/**
 * Column represents a database column
 */
export interface Column {
  id: string;
  name: string;
  type: string; // text, number, select, multi_select, checkbox, date
  options?: string[];
  required?: boolean;
}
/**
 * DataRecord represents a database record associated with a node
 */
export interface DataRecord {
  id: string;
  data: { [key: string]: any};
  created: string;
  modified: string;
}
/**
 * User represents a system user.
 */
export interface User {
  id: string;
  email: string;
  name: string;
  memberships?: Membership[];
  oauth_identities?: OAuthIdentity[];
  settings: UserSettings;
  created: string;
  modified: string;
}
/**
 * UserSettings represents global user preferences.
 */
export interface UserSettings {
  theme: string; // light, dark, system
  language: string; // en, fr, etc.
}
/**
 * OAuthIdentity represents a link between a local user and an OAuth2 provider.
 */
export interface OAuthIdentity {
  provider: string; // google, microsoft
  provider_id: string;
  email: string;
  last_login: string;
}
/**
 * Membership represents a user's relationship with an organization.
 */
export interface Membership {
  user_id: string;
  organization_id: string;
  organization_name?: string;
  role: UserRole;
  settings: MembershipSettings;
  created: string;
}
/**
 * MembershipSettings represents user preferences within a specific organization.
 */
export interface MembershipSettings {
  notifications: boolean;
}
/**
 * UserRole defines the permissions for a user.
 */
/**
 * UserRoleAdmin has full access to all resources and settings.
 */
export const UserRoleAdmin = "admin";
/**
 * UserRoleEditor can create and modify content but cannot manage users.
 */
export const UserRoleEditor = "editor";
/**
 * UserRoleViewer can only read content.
 */
export const UserRoleViewer = "viewer";
export type UserRole = typeof UserRoleAdmin | typeof UserRoleEditor | typeof UserRoleViewer;
/**
 * Organization represents a workspace or group of users.
 */
export interface Organization {
  id: string;
  name: string;
  quotas: Quota;
  settings: OrganizationSettings;
  created: string;
}
/**
 * OrganizationSettings represents organization-wide settings.
 */
export interface OrganizationSettings {
  allowed_domains?: string[];
  public_access: boolean;
}
/**
 * Quota defines limits for an organization.
 */
export interface Quota {
  max_pages: number /* int */;
  max_storage: number /* int64 */; // in bytes
  max_users: number /* int */;
}
/**
 * Invitation represents a request for a user to join an organization.
 */
export interface Invitation {
  id: string;
  email: string;
  organization_id: string;
  role: UserRole;
  token: string;
  expires_at: string;
  created: string;
}
/**
 * Session represents an active user session.
 */
export interface Session {
  id: string;
  user_id: string;
  expires_at: string;
}
/**
 * ContextKey is a custom type for context keys to avoid collisions.
 */
export type ContextKey = string;
/**
 * UserKey is the context key for the authenticated user.
 */
export const UserKey: ContextKey = "user";
/**
 * OrgKey is the context key for the active organization ID.
 */
export const OrgKey: ContextKey = "org";
/**
 * Asset represents an uploaded file/image associated with a node
 */
export interface Asset {
  id: string;
  name: string;
  mime_type: string;
  size: number /* int64 */;
  created: string;
  path: string;
}
/**
 * Page is kept for backward compatibility with existing storage methods
 */
export interface Page {
  id: string;
  title: string;
  content: string;
  created: string;
  modified: string;
  tags?: string[];
  path: string;
  favicon_url?: string;
}
/**
 * Database is kept for backward compatibility
 */
export interface Database {
  id: string;
  title: string;
  columns: Column[];
  created: string;
  modified: string;
  path: string;
}
/**
 * Commit represents a commit in git history.
 */
export interface Commit {
  hash: string;
  message: string;
  timestamp: string;
}
/**
 * CommitDetail contains full commit information.
 */
export interface CommitDetail {
  hash: string;
  timestamp: string;
  author: string;
  email: string;
  subject: string;
  body: string;
}
/**
 * SearchResult represents a single search result
 */
export interface SearchResult {
  type: string; // "page" or "record"
  node_id: string;
  record_id?: string;
  title: string;
  snippet: string;
  score: number /* float64 */;
  matches: { [key: string]: string};
  modified: string;
}
/**
 * SearchOptions defines parameters for a search
 */
export interface SearchOptions {
  query: string;
  limit?: number /* int */;
  match_title?: boolean;
  match_body?: boolean;
  match_fields?: boolean;
}

//////////
/*
Package errors defines structured error types for the API.
*/

/**
 * ErrorCode defines specific error types for the API.
 */
export type ErrorCode = string;
/**
 * ErrValidationFailed is returned when input data fails validation
 */
export const ErrValidationFailed: ErrorCode = "VALIDATION_FAILED";
/**
 * ErrMissingField is returned when a required field is missing
 */
export const ErrMissingField: ErrorCode = "MISSING_FIELD";
/**
 * ErrInvalidFormat is returned when a field has an invalid format
 */
export const ErrInvalidFormat: ErrorCode = "INVALID_FORMAT";
/**
 * ErrNotFound is returned when a resource is not found
 */
export const ErrNotFound: ErrorCode = "NOT_FOUND";
/**
 * ErrPageNotFound is returned when a page is not found
 */
export const ErrPageNotFound: ErrorCode = "PAGE_NOT_FOUND";
/**
 * ErrDatabaseNotFound is returned when a database is not found
 */
export const ErrDatabaseNotFound: ErrorCode = "DATABASE_NOT_FOUND";
/**
 * ErrFileNotFound is returned when a file is not found
 */
export const ErrFileNotFound: ErrorCode = "FILE_NOT_FOUND";
/**
 * ErrStorageError is returned when a storage operation fails
 */
export const ErrStorageError: ErrorCode = "STORAGE_ERROR";
/**
 * ErrInternal is returned when an unexpected server error occurs
 */
export const ErrInternal: ErrorCode = "INTERNAL_ERROR";
/**
 * ErrNotImplemented is returned when a feature is not implemented
 */
export const ErrNotImplemented: ErrorCode = "NOT_IMPLEMENTED";
/**
 * ErrConflict is returned when there is a resource conflict
 */
export const ErrConflict: ErrorCode = "CONFLICT";
/**
 * ErrUnauthorized is returned when authentication is missing or invalid
 */
export const ErrUnauthorized: ErrorCode = "UNAUTHORIZED";
/**
 * ErrForbidden is returned when a user has insufficient permissions
 */
export const ErrForbidden: ErrorCode = "FORBIDDEN";
/**
 * ErrorDetails defines the structured error information in a response.
 */
export interface ErrorDetails {
  code: ErrorCode;
  message: string;
}
/**
 * ErrorResponse is the standard API error response.
 */
export interface ErrorResponse {
  error: ErrorDetails;
  details?: { [key: string]: any};
}
/**
 * ErrorWithStatus is an error that includes an HTTP status code and error code.
 */
export type ErrorWithStatus = any;
/**
 * APIError is a concrete error type with status code, code, and optional details.
 */
export interface APIError {
}

