// Code generated by tygo. DO NOT EDIT.

//////////
// source: errors.go
/*
Package dto defines API request/response types and error handling.

This package contains all types used for HTTP API communication via goty:
  - Request types with path/query/json struct tags for parameter binding
  - Response types with string IDs and RFC3339 timestamps for JSON serialization
  - Structured error types with HTTP status codes and error codes
  - API-specific types (Property, UserRole, NodeType, Settings, etc.)

The dto package is the API contract layer, fully self-contained with no
dependency on the entity package. This ensures that changes to internal
domain models (entity) do not accidentally affect the API contract.

Conversion between dto and entity types is handled by the handlers package
(in convert.go), which imports both packages.

Error handling follows a structured pattern:
  - ErrorCode provides machine-readable error classification
  - APIError wraps errors with HTTP status codes and details
  - Constructor functions (NotFound, BadRequest, etc.) create common errors
*/

/**
 * ErrorCode defines specific error types for the API.
 */
/**
 * ErrorCodeValidationFailed is returned when input data fails validation.
 */
export const ErrorCodeValidationFailed = "VALIDATION_FAILED";
/**
 * ErrorCodeMissingField is returned when a required field is missing.
 */
export const ErrorCodeMissingField = "MISSING_FIELD";
/**
 * ErrorCodeInvalidFormat is returned when a field has an invalid format.
 */
export const ErrorCodeInvalidFormat = "INVALID_FORMAT";
/**
 * ErrorCodeNotFound is returned when a resource is not found.
 */
export const ErrorCodeNotFound = "NOT_FOUND";
/**
 * ErrorCodePageNotFound is returned when a page is not found.
 */
export const ErrorCodePageNotFound = "PAGE_NOT_FOUND";
/**
 * ErrorCodeTableNotFound is returned when a table is not found.
 */
export const ErrorCodeTableNotFound = "TABLE_NOT_FOUND";
/**
 * ErrorCodeFileNotFound is returned when a file is not found.
 */
export const ErrorCodeFileNotFound = "FILE_NOT_FOUND";
/**
 * ErrorCodeStorageError is returned when a storage operation fails.
 */
export const ErrorCodeStorageError = "STORAGE_ERROR";
/**
 * ErrorCodeInternal is returned when an unexpected server error occurs.
 */
export const ErrorCodeInternal = "INTERNAL_ERROR";
/**
 * ErrorCodeNotImplemented is returned when a feature is not implemented.
 */
export const ErrorCodeNotImplemented = "NOT_IMPLEMENTED";
/**
 * ErrorCodeConflict is returned when there is a resource conflict.
 */
export const ErrorCodeConflict = "CONFLICT";
/**
 * ErrorCodeUnauthorized is returned when authentication is missing or invalid.
 */
export const ErrorCodeUnauthorized = "UNAUTHORIZED";
/**
 * ErrorCodeForbidden is returned when a user has insufficient permissions.
 */
export const ErrorCodeForbidden = "FORBIDDEN";
/**
 * ErrorCodeInvalidProvider is returned when an OAuth provider is unknown.
 */
export const ErrorCodeInvalidProvider = "INVALID_PROVIDER";
/**
 * ErrorCodeOAuthError is returned when an OAuth operation fails.
 */
export const ErrorCodeOAuthError = "OAUTH_ERROR";
/**
 * ErrorCodeExpired is returned when a resource has expired.
 */
export const ErrorCodeExpired = "EXPIRED";
export type ErrorCode = typeof ErrorCodeValidationFailed | typeof ErrorCodeMissingField | typeof ErrorCodeInvalidFormat | typeof ErrorCodeNotFound | typeof ErrorCodePageNotFound | typeof ErrorCodeTableNotFound | typeof ErrorCodeFileNotFound | typeof ErrorCodeStorageError | typeof ErrorCodeInternal | typeof ErrorCodeNotImplemented | typeof ErrorCodeConflict | typeof ErrorCodeUnauthorized | typeof ErrorCodeForbidden | typeof ErrorCodeInvalidProvider | typeof ErrorCodeOAuthError | typeof ErrorCodeExpired;
/**
 * ErrorDetails defines the structured error information in a response.
 */
export interface ErrorDetails {
  code: ErrorCode;
  message: string;
}
/**
 * ErrorResponse is the standard API error response.
 */
export interface ErrorResponse {
  error: ErrorDetails;
  details?: { [key: string]: any};
}
/**
 * ErrorWithStatus is an error that includes an HTTP status code and error code.
 */
export type ErrorWithStatus = any;
/**
 * APIError is a concrete error type with status code and optional details.
 */
export interface APIError {
}

//////////
// source: request.go

/**
 * LoginRequest is a request to log in.
 */
export interface LoginRequest {
  email: string;
  password: string;
}
/**
 * RegisterRequest is a request to register a new user.
 */
export interface RegisterRequest {
  email: string;
  password: string;
  name: string;
}
/**
 * GetMeRequest is a request to get current user info.
 */
export interface GetMeRequest {
}
/**
 * ListPagesRequest is a request to list all pages.
 */
export interface ListPagesRequest {
}
/**
 * GetPageRequest is a request to get a page.
 */
export interface GetPageRequest {
}
/**
 * CreatePageRequest is a request to create a page.
 */
export interface CreatePageRequest {
  title: string;
  content: string;
}
/**
 * UpdatePageRequest is a request to update a page.
 */
export interface UpdatePageRequest {
  title: string;
  content: string;
}
/**
 * DeletePageRequest is a request to delete a page.
 */
export interface DeletePageRequest {
}
/**
 * ListPageVersionsRequest is a request to list page version history.
 */
export interface ListPageVersionsRequest {
  Limit: number /* int */; // Max commits to return (1-1000, default 1000).
}
/**
 * GetPageVersionRequest is a request to get a specific page version.
 */
export interface GetPageVersionRequest {
}
/**
 * ListTablesRequest is a request to list tables.
 */
export interface ListTablesRequest {
}
/**
 * GetTableRequest is a request to get a table.
 */
export interface GetTableRequest {
}
/**
 * CreateTableRequest is a request to create a table.
 */
export interface CreateTableRequest {
  title: string;
  properties: Property[];
}
/**
 * UpdateTableRequest is a request to update a table.
 */
export interface UpdateTableRequest {
  title: string;
  properties: Property[];
}
/**
 * DeleteTableRequest is a request to delete a table.
 */
export interface DeleteTableRequest {
}
/**
 * ListRecordsRequest is a request to list records in a table.
 */
export interface ListRecordsRequest {
  Offset: number /* int */;
  Limit: number /* int */;
}
/**
 * CreateRecordRequest is a request to create a record.
 */
export interface CreateRecordRequest {
  data: { [key: string]: any};
}
/**
 * UpdateRecordRequest is a request to update a record.
 */
export interface UpdateRecordRequest {
  data: { [key: string]: any};
}
/**
 * GetRecordRequest is a request to get a record.
 */
export interface GetRecordRequest {
}
/**
 * DeleteRecordRequest is a request to delete a record.
 */
export interface DeleteRecordRequest {
}
/**
 * ListNodesRequest is a request to list nodes.
 */
export interface ListNodesRequest {
}
/**
 * GetNodeRequest is a request to get a node.
 */
export interface GetNodeRequest {
}
/**
 * CreateNodeRequest is a request to create a node.
 */
export interface CreateNodeRequest {
  parent_id?: string;
  title: string;
  type: NodeType;
}
/**
 * ListPageAssetsRequest is a request to list assets in a page.
 */
export interface ListPageAssetsRequest {
}
/**
 * UploadPageAssetRequest is a request to upload an asset to a page.
 */
export interface UploadPageAssetRequest {
}
/**
 * DeletePageAssetRequest is a request to delete an asset from a page.
 */
export interface DeletePageAssetRequest {
}
/**
 * ServeAssetRequest is a request to serve an asset file directly.
 */
export interface ServeAssetRequest {
}
/**
 * SearchRequest is a request to search pages and tables.
 */
export interface SearchRequest {
  query: string;
  limit?: number /* int */;
  match_title?: boolean;
  match_body?: boolean;
  match_fields?: boolean;
}
/**
 * CreateInvitationRequest is a request to create an invitation.
 */
export interface CreateInvitationRequest {
  email: string;
  role: UserRole;
}
/**
 * ListInvitationsRequest is a request to list invitations for an organization.
 */
export interface ListInvitationsRequest {
}
/**
 * AcceptInvitationRequest is a request to accept an invitation.
 */
export interface AcceptInvitationRequest {
  token: string;
  password: string;
  name: string;
}
/**
 * SwitchOrgRequest is a request to switch active organization.
 */
export interface SwitchOrgRequest {
  org_id: string;
}
/**
 * UpdateMembershipSettingsRequest is a request to update user preferences within an organization.
 */
export interface UpdateMembershipSettingsRequest {
  settings: MembershipSettings;
}
/**
 * UpdateOrgPreferencesRequest is a request to update organization-wide preferences.
 */
export interface UpdateOrgPreferencesRequest {
  settings: OrganizationSettings;
}
/**
 * GetOrganizationRequest is a request to get organization details.
 */
export interface GetOrganizationRequest {
}
/**
 * UpdateOrganizationRequest is a request to update organization details.
 */
export interface UpdateOrganizationRequest {
  name?: string;
}
/**
 * CreateOrganizationRequest is a request to create a new organization.
 */
export interface CreateOrganizationRequest {
  name: string;
  welcome_page_title?: string;
  welcome_page_content?: string;
}
/**
 * GetGitRemoteRequest is a request to get the git remote for an organization.
 */
export interface GetGitRemoteRequest {
}
/**
 * UpdateGitRemoteRequest is a request to set (create or update) the git remote for an organization.
 */
export interface UpdateGitRemoteRequest {
  url: string;
  type: string; // github, gitlab, custom
  auth_type: string; // token, ssh
  token?: string;
}
/**
 * DeleteGitRequest is a request to delete the git remote for an organization.
 */
export interface DeleteGitRequest {
}
/**
 * PushGitRequest is a request to push to the git remote.
 */
export interface PushGitRequest {
}
/**
 * HealthRequest is a request to check system health.
 */
export interface HealthRequest {
}
/**
 * ListUsersRequest is a request to list users.
 */
export interface ListUsersRequest {
}
/**
 * UpdateUserRoleRequest is a request to update a user's role.
 */
export interface UpdateUserRoleRequest {
  user_id: string;
  role: UserRole;
}
/**
 * UpdateUserSettingsRequest is a request to update user global settings.
 */
export interface UpdateUserSettingsRequest {
  settings: UserSettings;
}
/**
 * AdminStatsRequest is a request to get admin stats.
 */
export interface AdminStatsRequest {
}
/**
 * AdminUsersRequest is a request to list all users (admin only).
 */
export interface AdminUsersRequest {
}
/**
 * AdminOrgsRequest is a request to list all organizations (admin only).
 */
export interface AdminOrgsRequest {
}

//////////
// source: response.go

/**
 * OkResponse is a simple success response.
 */
export interface OkResponse {
  ok: boolean;
}
/**
 * AuthResponse is a response containing authentication token and user info.
 * Used by login, register, and invitation acceptance endpoints.
 */
export interface AuthResponse {
  token: string;
  user?: UserResponse;
}
/**
 * ListPagesResponse is a response containing a list of pages.
 */
export interface ListPagesResponse {
  pages: PageSummary[];
}
/**
 * PageSummary is a brief representation of a page for list responses.
 */
export interface PageSummary {
  id: string;
  title: string;
  created: string;
  modified: string;
}
/**
 * GetPageResponse is a response containing a page.
 */
export interface GetPageResponse {
  id: string;
  title: string;
  content: string;
}
/**
 * CreatePageResponse is a response from creating a page.
 */
export interface CreatePageResponse {
  id: string;
}
/**
 * UpdatePageResponse is a response from updating a page.
 */
export interface UpdatePageResponse {
  id: string;
}
/**
 * DeletePageResponse is a response from deleting a page.
 */
export type DeletePageResponse = OkResponse;
/**
 * ListPageVersionsResponse is a response containing page version history.
 */
export interface ListPageVersionsResponse {
  history: (Commit | undefined)[];
}
/**
 * GetPageVersionResponse is a response containing page content at a version.
 */
export interface GetPageVersionResponse {
  content: string;
}
/**
 * ListTablesResponse is a response containing a list of tables.
 */
export interface ListTablesResponse {
  tables: TableSummary[];
}
/**
 * TableSummary is a brief representation of a table for list responses.
 */
export interface TableSummary {
  id: string;
  title: string;
  created: string;
  modified: string;
}
/**
 * GetTableResponse is a response containing a table.
 */
export interface GetTableResponse {
  id: string;
  title: string;
  properties: Property[];
  created: string;
  modified: string;
}
/**
 * CreateTableResponse is a response from creating a table.
 */
export interface CreateTableResponse {
  id: string;
}
/**
 * UpdateTableResponse is a response from updating a table.
 */
export interface UpdateTableResponse {
  id: string;
}
/**
 * DeleteTableResponse is a response from deleting a table.
 */
export type DeleteTableResponse = OkResponse;
/**
 * ListRecordsResponse is a response containing a list of records.
 */
export interface ListRecordsResponse {
  records: DataRecordResponse[];
}
/**
 * CreateRecordResponse is a response from creating a record.
 */
export interface CreateRecordResponse {
  id: string;
}
/**
 * UpdateRecordResponse is a response from updating a record.
 */
export interface UpdateRecordResponse {
  id: string;
}
/**
 * GetRecordResponse is a response containing a record.
 */
export interface GetRecordResponse {
  id: string;
  data: { [key: string]: any};
  created: string;
  modified: string;
}
/**
 * DeleteRecordResponse is a response from deleting a record.
 */
export type DeleteRecordResponse = OkResponse;
/**
 * ListNodesResponse is a response containing a list of nodes.
 */
export interface ListNodesResponse {
  nodes: NodeResponse[];
}
/**
 * ListPageAssetsResponse is a response containing a list of assets.
 */
export interface ListPageAssetsResponse {
  assets: AssetSummary[];
}
/**
 * AssetSummary is a brief representation of an asset for list responses.
 */
export interface AssetSummary {
  id: string;
  name: string;
  size: number /* int64 */;
  mime_type: string;
  created: string;
  url: string;
}
/**
 * UploadPageAssetResponse is a response from uploading an asset.
 */
export interface UploadPageAssetResponse {
  id: string;
  name: string;
  size: number /* int64 */;
  mime_type: string;
}
/**
 * DeletePageAssetResponse is a response from deleting an asset.
 */
export type DeletePageAssetResponse = OkResponse;
/**
 * ServeAssetResponse wraps the binary asset data.
 */
export interface ServeAssetResponse {
  data: string;
  mime_type: string;
}
/**
 * SearchResponse is the response to a search request.
 */
export interface SearchResponse {
  results: SearchResult[];
}
/**
 * ListInvitationsResponse is a response containing a list of invitations.
 */
export interface ListInvitationsResponse {
  invitations: InvitationResponse[];
}
/**
 * SwitchOrgResponse is a response from switching organization.
 */
export interface SwitchOrgResponse {
  token: string;
  user?: UserResponse;
}
/**
 * HealthResponse is a response from a health check.
 */
export interface HealthResponse {
  status: string;
  version: string;
}
/**
 * ListUsersResponse is a response containing a list of users.
 */
export interface ListUsersResponse {
  users: UserResponse[];
}
/**
 * UserResponse is the API representation of a user.
 */
export interface UserResponse {
  id: string;
  email: string;
  name: string;
  is_global_admin?: boolean;
  oauth_identities?: OAuthIdentity[];
  settings: UserSettings;
  created: string;
  modified: string;
  memberships?: MembershipResponse[];
  organization_id?: string;
  role?: UserRole;
}
/**
 * MembershipResponse is the API representation of a membership.
 */
export interface MembershipResponse {
  id: string;
  user_id: string;
  organization_id: string;
  organization_name?: string;
  role: UserRole;
  settings: MembershipSettings;
  created: string;
}
/**
 * InvitationResponse is the API representation of an invitation (excludes Token).
 */
export interface InvitationResponse {
  id: string;
  email: string;
  organization_id: string;
  role: UserRole;
  expires_at: string;
  created: string;
}
/**
 * OrganizationResponse is the API representation of an organization.
 */
export interface OrganizationResponse {
  id: string;
  name: string;
  quotas: OrganizationQuota;
  settings: OrganizationSettings;
  created: string;
}
/**
 * GitRemoteResponse is the API representation of a git remote.
 * Each organization has at most one remote, identified by OrganizationID.
 */
export interface GitRemoteResponse {
  organization_id: string;
  url: string;
  type: string;
  auth_type: string;
  created: string;
  last_sync?: string;
}
/**
 * NodeResponse is the API representation of a node.
 */
export interface NodeResponse {
  id: string;
  parent_id?: string;
  title: string;
  content?: string;
  properties?: Property[];
  created: string;
  modified: string;
  tags?: string[];
  favicon_url?: string;
  type: NodeType;
  children?: NodeResponse[];
}
/**
 * DataRecordResponse is the API representation of a data record.
 */
export interface DataRecordResponse {
  id: string;
  data: { [key: string]: any};
  created: string;
  modified: string;
}
/**
 * AdminStatsResponse contains server-wide statistics.
 */
export interface AdminStatsResponse {
  user_count: number /* int */;
  org_count: number /* int */;
}
/**
 * AdminUsersResponse contains all users in the system.
 */
export interface AdminUsersResponse {
  users: UserResponse[];
}
/**
 * AdminOrgsResponse contains all organizations in the system.
 */
export interface AdminOrgsResponse {
  organizations: OrganizationResponse[];
}

//////////
// source: types.go

/**
 * PropertyType represents the type of a table property.
 */
/**
 * PropertyTypeText stores plain text values.
 */
export const PropertyTypeText = "text";
/**
 * PropertyTypeNumber stores numeric values (integer or float).
 */
export const PropertyTypeNumber = "number";
/**
 * PropertyTypeCheckbox stores boolean values.
 */
export const PropertyTypeCheckbox = "checkbox";
/**
 * PropertyTypeDate stores ISO8601 date strings.
 */
export const PropertyTypeDate = "date";
/**
 * PropertyTypeSelect stores a single selection from predefined options.
 */
export const PropertyTypeSelect = "select";
/**
 * PropertyTypeMultiSelect stores multiple selections from predefined options.
 */
export const PropertyTypeMultiSelect = "multi_select";
/**
 * PropertyTypeURL stores URLs with validation.
 */
export const PropertyTypeURL = "url";
/**
 * PropertyTypeEmail stores email addresses with validation.
 */
export const PropertyTypeEmail = "email";
/**
 * PropertyTypePhone stores phone numbers with validation.
 */
export const PropertyTypePhone = "phone";
export type PropertyType = typeof PropertyTypeText | typeof PropertyTypeNumber | typeof PropertyTypeCheckbox | typeof PropertyTypeDate | typeof PropertyTypeSelect | typeof PropertyTypeMultiSelect | typeof PropertyTypeURL | typeof PropertyTypeEmail | typeof PropertyTypePhone;
/**
 * SelectOption represents an option for select/multi_select properties.
 */
export interface SelectOption {
  id: string;
  name: string;
  color?: string;
}
/**
 * Property represents a table column with its configuration.
 */
export interface Property {
  name: string;
  type: PropertyType;
  required?: boolean;
  /**
   * Options contains the allowed values for select and multi_select properties.
   * Each option has an ID (used in storage), name (display), and optional color.
   */
  options?: SelectOption[];
}
/**
 * UserRole defines the permissions for a user.
 */
/**
 * UserRoleAdmin has full access to all resources and settings within an organization.
 */
export const UserRoleAdmin = "admin";
/**
 * UserRoleEditor can create and modify content but cannot manage users.
 */
export const UserRoleEditor = "editor";
/**
 * UserRoleViewer can only read content.
 */
export const UserRoleViewer = "viewer";
export type UserRole = typeof UserRoleAdmin | typeof UserRoleEditor | typeof UserRoleViewer;
/**
 * NodeType defines what features are enabled for a node.
 */
/**
 * NodeTypeDocument represents a markdown document.
 */
export const NodeTypeDocument = "document";
/**
 * NodeTypeTable represents a structured table.
 */
export const NodeTypeTable = "table";
/**
 * NodeTypeHybrid represents an entity that is both a document and a table.
 */
export const NodeTypeHybrid = "hybrid";
export type NodeType = typeof NodeTypeDocument | typeof NodeTypeTable | typeof NodeTypeHybrid;
/**
 * UserSettings represents global user preferences.
 */
export interface UserSettings {
  theme: string;
  language: string;
}
/**
 * OAuthIdentity represents a link between a local user and an OAuth2 provider.
 */
export interface OAuthIdentity {
  provider: string;
  provider_id: string;
  email: string;
  last_login: string;
}
/**
 * MembershipSettings represents user preferences within a specific organization.
 */
export interface MembershipSettings {
  notifications: boolean;
}
/**
 * OrganizationQuota defines limits for an organization.
 */
export interface OrganizationQuota {
  max_pages: number /* int */;
  max_storage: number /* int64 */;
  max_users: number /* int */;
}
/**
 * UserQuota defines limits for a user.
 */
export interface UserQuota {
  max_orgs: number /* int */;
}
/**
 * OrganizationSettings represents organization-wide settings.
 */
export interface OrganizationSettings {
  allowed_domains?: string[];
  public_access: boolean;
  git_auto_push: boolean;
}
/**
 * Commit represents a commit in git history.
 */
export interface Commit {
  hash: string;
  message: string;
  timestamp: string;
}
/**
 * SearchResult represents a single search result.
 */
export interface SearchResult {
  type: string; // "page" or "record"
  node_id: string;
  record_id?: string;
  title: string;
  snippet: string;
  score: number /* float64 */;
  matches: { [key: string]: string};
  modified: string;
}

//////////
// source: validate.go

/**
 * Validatable is implemented by request types that can validate their fields.
 * The Wrap functions in handler_wrapper.go use this interface as a type
 * constraint to ensure all request types provide validation.
 */
export type Validatable = any;
