// Code generated by tygo. DO NOT EDIT.

//////////
// source: errors.go
/*
Package dto defines API request/response types and error handling.

This package contains all types used for HTTP API communication via goty:
  - Request types with path/query/json struct tags for parameter binding
  - Response types with string IDs and RFC3339 timestamps for JSON serialization
  - Structured error types with HTTP status codes and error codes
  - API-specific types (Property, UserRole, NodeType, Settings, etc.)

The dto package is the API contract layer, fully self-contained with no
dependency on the entity package. This ensures that changes to internal
domain models (entity) do not accidentally affect the API contract.

Conversion between dto and entity types is handled by the handlers package
(in convert.go), which imports both packages.

Error handling follows a structured pattern:
  - ErrorCode provides machine-readable error classification
  - APIError wraps errors with HTTP status codes and details
  - Constructor functions (NotFound, BadRequest, etc.) create common errors
*/

/**
 * ErrorCode defines specific error types for the API.
 */
/**
 * ErrorCodeValidationFailed is returned when input data fails validation.
 */
export const ErrorCodeValidationFailed = "VALIDATION_FAILED";
/**
 * ErrorCodeMissingField is returned when a required field is missing.
 */
export const ErrorCodeMissingField = "MISSING_FIELD";
/**
 * ErrorCodeInvalidFormat is returned when a field has an invalid format.
 */
export const ErrorCodeInvalidFormat = "INVALID_FORMAT";
/**
 * ErrorCodeNotFound is returned when a resource is not found.
 */
export const ErrorCodeNotFound = "NOT_FOUND";
/**
 * ErrorCodeNodeNotFound is returned when a node is not found.
 */
export const ErrorCodeNodeNotFound = "NODE_NOT_FOUND";
/**
 * ErrorCodeTableNotFound is returned when a table is not found.
 */
export const ErrorCodeTableNotFound = "TABLE_NOT_FOUND";
/**
 * ErrorCodeFileNotFound is returned when a file is not found.
 */
export const ErrorCodeFileNotFound = "FILE_NOT_FOUND";
/**
 * ErrorCodeStorageError is returned when a storage operation fails.
 */
export const ErrorCodeStorageError = "STORAGE_ERROR";
/**
 * ErrorCodeInternal is returned when an unexpected server error occurs.
 */
export const ErrorCodeInternal = "INTERNAL_ERROR";
/**
 * ErrorCodeNotImplemented is returned when a feature is not implemented.
 */
export const ErrorCodeNotImplemented = "NOT_IMPLEMENTED";
/**
 * ErrorCodeConflict is returned when there is a resource conflict.
 */
export const ErrorCodeConflict = "CONFLICT";
/**
 * ErrorCodeUnauthorized is returned when authentication is missing or invalid.
 */
export const ErrorCodeUnauthorized = "UNAUTHORIZED";
/**
 * ErrorCodeForbidden is returned when a user has insufficient permissions.
 */
export const ErrorCodeForbidden = "FORBIDDEN";
/**
 * ErrorCodeInvalidProvider is returned when an OAuth provider is unknown.
 */
export const ErrorCodeInvalidProvider = "INVALID_PROVIDER";
/**
 * ErrorCodeOAuthError is returned when an OAuth operation fails.
 */
export const ErrorCodeOAuthError = "OAUTH_ERROR";
/**
 * ErrorCodeExpired is returned when a resource has expired.
 */
export const ErrorCodeExpired = "EXPIRED";
/**
 * ErrorCodeRateLimitExceeded is returned when rate limit is exceeded.
 */
export const ErrorCodeRateLimitExceeded = "RATE_LIMIT_EXCEEDED";
/**
 * ErrorCodeCannotUnlinkOnlyAuth is returned when trying to unlink the only authentication method.
 */
export const ErrorCodeCannotUnlinkOnlyAuth = "CANNOT_UNLINK_ONLY_AUTH";
/**
 * ErrorCodeProviderAlreadyLinked is returned when trying to link an already linked provider.
 */
export const ErrorCodeProviderAlreadyLinked = "PROVIDER_ALREADY_LINKED";
/**
 * ErrorCodeProviderNotLinked is returned when trying to unlink a provider that is not linked.
 */
export const ErrorCodeProviderNotLinked = "PROVIDER_NOT_LINKED";
/**
 * ErrorCodeEmailInUse is returned when an email is already in use by another account.
 */
export const ErrorCodeEmailInUse = "EMAIL_IN_USE";
/**
 * ErrorCodeQuotaExceeded is returned when a server-wide quota is exceeded.
 */
export const ErrorCodeQuotaExceeded = "QUOTA_EXCEEDED";
/**
 * ErrorCodePayloadTooLarge is returned when the request body exceeds the size limit.
 */
export const ErrorCodePayloadTooLarge = "PAYLOAD_TOO_LARGE";
export type ErrorCode = typeof ErrorCodeValidationFailed | typeof ErrorCodeMissingField | typeof ErrorCodeInvalidFormat | typeof ErrorCodeNotFound | typeof ErrorCodeNodeNotFound | typeof ErrorCodeTableNotFound | typeof ErrorCodeFileNotFound | typeof ErrorCodeStorageError | typeof ErrorCodeInternal | typeof ErrorCodeNotImplemented | typeof ErrorCodeConflict | typeof ErrorCodeUnauthorized | typeof ErrorCodeForbidden | typeof ErrorCodeInvalidProvider | typeof ErrorCodeOAuthError | typeof ErrorCodeExpired | typeof ErrorCodeRateLimitExceeded | typeof ErrorCodeCannotUnlinkOnlyAuth | typeof ErrorCodeProviderAlreadyLinked | typeof ErrorCodeProviderNotLinked | typeof ErrorCodeEmailInUse | typeof ErrorCodeQuotaExceeded | typeof ErrorCodePayloadTooLarge;
/**
 * ErrorDetails defines the structured error information in a response.
 */
export interface ErrorDetails {
  code: ErrorCode;
  message: string;
}
/**
 * ErrorResponse is the standard API error response.
 */
export interface ErrorResponse {
  error: ErrorDetails;
  details?: { [key: string]: any};
}
/**
 * ErrorWithStatus is an error that includes an HTTP status code and error code.
 */
export type ErrorWithStatus = any;
/**
 * APIError is a concrete error type with status code and optional details.
 */
export interface APIError {
}

//////////
// source: request.go

/**
 * LoginRequest is a request to log in.
 */
export interface LoginRequest {
  email: string;
  password: string;
}
/**
 * RegisterRequest is a request to register a new user.
 */
export interface RegisterRequest {
  email: string;
  password: string;
  name: string;
}
/**
 * GetMeRequest is a request to get current user info.
 */
export interface GetMeRequest {
}
/**
 * CreatePageRequest is a request to create a page under a parent node.
 * The parent ID is in the path ({id}); use "0" for root.
 */
export interface CreatePageRequest {
  title: string;
  content?: string;
}
/**
 * GetPageRequest is a request to get a page's content.
 */
export interface GetPageRequest {
}
/**
 * UpdatePageRequest is a request to update a page's content.
 */
export interface UpdatePageRequest {
  title: string;
  content: string;
}
/**
 * DeletePageRequest is a request to delete a page from a node.
 * This removes the index.md but keeps the node directory if table data exists.
 */
export interface DeletePageRequest {
}
/**
 * DeleteNodeRequest is a request to delete a node.
 */
export interface DeleteNodeRequest {
}
/**
 * ListNodeVersionsRequest is a request to list node version history.
 */
export interface ListNodeVersionsRequest {
  Limit: number /* int */; // Max commits to return (1-1000, default 1000).
}
/**
 * GetNodeVersionRequest is a request to get a specific node version.
 */
export interface GetNodeVersionRequest {
}
/**
 * GetTableRequest is a request to get a table.
 * Now used for /nodes/{id}/table endpoint.
 */
export interface GetTableRequest {
}
/**
 * CreateTableRequest is a request to create a table under a parent node.
 * The parent ID is in the path ({id}); use "0" for root.
 */
export interface CreateTableRequest {
  title: string;
  properties: Property[];
}
/**
 * UpdateTableRequest is a request to update a table.
 * Now used for /nodes/{id}/table endpoint.
 */
export interface UpdateTableRequest {
  title: string;
  properties: Property[];
}
/**
 * DeleteTableRequest is a request to delete a table from a node.
 * This removes the metadata.json and data.jsonl but keeps the node directory if page exists.
 */
export interface DeleteTableRequest {
}
/**
 * ListRecordsRequest is a request to list records in a table.
 * Now used for /nodes/{id}/table/records endpoint.
 */
export interface ListRecordsRequest {
  Offset: number /* int */;
  Limit: number /* int */;
}
/**
 * CreateRecordRequest is a request to create a record.
 * Now used for /nodes/{id}/table/records/create endpoint.
 */
export interface CreateRecordRequest {
  data: { [key: string]: any};
}
/**
 * UpdateRecordRequest is a request to update a record.
 * Now used for /nodes/{id}/table/records/{rid} endpoint.
 */
export interface UpdateRecordRequest {
  data: { [key: string]: any};
}
/**
 * GetRecordRequest is a request to get a record.
 * Now used for /nodes/{id}/table/records/{rid} endpoint.
 */
export interface GetRecordRequest {
}
/**
 * DeleteRecordRequest is a request to delete a record.
 * Now used for /nodes/{id}/table/records/{rid}/delete endpoint.
 */
export interface DeleteRecordRequest {
}
/**
 * ListNodesRequest is a request to list nodes.
 */
export interface ListNodesRequest {
}
/**
 * GetNodeRequest is a request to get a node.
 */
export interface GetNodeRequest {
}
/**
 * ListNodeChildrenRequest is a request to list children of a node.
 */
export interface ListNodeChildrenRequest {
}
/**
 * ListNodeAssetsRequest is a request to list assets in a node.
 */
export interface ListNodeAssetsRequest {
}
/**
 * UploadNodeAssetRequest is a request to upload an asset to a node.
 */
export interface UploadNodeAssetRequest {
}
/**
 * DeleteNodeAssetRequest is a request to delete an asset from a node.
 */
export interface DeleteNodeAssetRequest {
}
/**
 * ServeAssetRequest is a request to serve an asset file directly.
 */
export interface ServeAssetRequest {
}
/**
 * SearchRequest is a request to search pages and tables.
 */
export interface SearchRequest {
  query: string;
  limit?: number /* int */;
  match_title?: boolean;
  match_body?: boolean;
  match_fields?: boolean;
}
/**
 * CreateOrgInvitationRequest is a request to create an organization invitation.
 */
export interface CreateOrgInvitationRequest {
  email: string;
  role: OrganizationRole;
  locale?: string; // Optional: language for invitation email (en, fr, de, es)
}
/**
 * CreateWSInvitationRequest is a request to create a workspace invitation.
 */
export interface CreateWSInvitationRequest {
  email: string;
  role: WorkspaceRole;
  locale?: string; // Optional: language for invitation email (en, fr, de, es)
}
/**
 * ListOrgInvitationsRequest is a request to list invitations for an organization.
 */
export interface ListOrgInvitationsRequest {
}
/**
 * ListWSInvitationsRequest is a request to list invitations for a workspace.
 */
export interface ListWSInvitationsRequest {
}
/**
 * AcceptInvitationRequest is a request to accept an invitation.
 */
export interface AcceptInvitationRequest {
  token: string;
  password: string;
  name: string;
}
/**
 * SwitchOrgRequest is a request to switch active organization.
 */
export interface SwitchOrgRequest {
  org_id: string;
}
/**
 * SwitchWorkspaceRequest is a request to switch active workspace.
 */
export interface SwitchWorkspaceRequest {
  ws_id: string;
}
/**
 * UpdateWSMembershipSettingsRequest is a request to update user preferences within a workspace.
 */
export interface UpdateWSMembershipSettingsRequest {
  settings: WorkspaceMembershipSettings;
}
/**
 * UpdateOrgPreferencesRequest is a request to update organization-wide preferences.
 */
export interface UpdateOrgPreferencesRequest {
  settings: OrganizationSettings;
}
/**
 * GetOrganizationRequest is a request to get organization details.
 */
export interface GetOrganizationRequest {
}
/**
 * UpdateOrganizationRequest is a request to update organization details.
 */
export interface UpdateOrganizationRequest {
  name?: string;
}
/**
 * CreateOrganizationRequest is a request to create a new organization.
 */
export interface CreateOrganizationRequest {
  name: string;
}
/**
 * CreateWorkspaceRequest is a request to create a new workspace within an organization.
 */
export interface CreateWorkspaceRequest {
  name: string;
}
/**
 * GetWorkspaceRequest is a request to get workspace details.
 */
export interface GetWorkspaceRequest {
}
/**
 * UpdateWorkspaceRequest is a request to update workspace details.
 */
export interface UpdateWorkspaceRequest {
  name?: string;
}
/**
 * GetGitRemoteRequest is a request to get the git remote for a workspace.
 */
export interface GetGitRemoteRequest {
}
/**
 * UpdateGitRemoteRequest is a request to set (create or update) the git remote for a workspace.
 */
export interface UpdateGitRemoteRequest {
  url: string;
  type: string; // github, gitlab, custom
  auth_type: string; // token, ssh
  token?: string;
}
/**
 * DeleteGitRequest is a request to delete the git remote for a workspace.
 */
export interface DeleteGitRequest {
}
/**
 * PushGitRequest is a request to push to the git remote.
 */
export interface PushGitRequest {
}
/**
 * ChangeEmailRequest is a request to change the user's email address.
 */
export interface ChangeEmailRequest {
  new_email: string;
  password: string; // Required for security verification
}
/**
 * SendVerificationEmailRequest is a request to send a verification email.
 */
export interface SendVerificationEmailRequest {
}
/**
 * VerifyEmailRequest is a request to verify an email via magic link token.
 */
export interface VerifyEmailRequest {
}
/**
 * LinkOAuthAccountRequest is a request to initiate linking an OAuth provider.
 */
export interface LinkOAuthAccountRequest {
  provider: OAuthProvider;
}
/**
 * UnlinkOAuthAccountRequest is a request to unlink an OAuth provider.
 */
export interface UnlinkOAuthAccountRequest {
  provider: OAuthProvider;
}
/**
 * HealthRequest is a request to check system health.
 */
export interface HealthRequest {
}
/**
 * ProvidersRequest is a request to list configured OAuth providers.
 */
export interface ProvidersRequest {
}
/**
 * LogoutRequest is a request to logout (revoke current session).
 */
export interface LogoutRequest {
}
/**
 * ListSessionsRequest is a request to list user's active sessions.
 */
export interface ListSessionsRequest {
}
/**
 * RevokeSessionRequest is a request to revoke a specific session.
 */
export interface RevokeSessionRequest {
  session_id: string;
}
/**
 * RevokeAllSessionsRequest is a request to revoke all sessions (logout everywhere).
 */
export interface RevokeAllSessionsRequest {
}
/**
 * ListUsersRequest is a request to list users.
 */
export interface ListUsersRequest {
}
/**
 * UpdateOrgMemberRoleRequest is a request to update a user's organization role.
 */
export interface UpdateOrgMemberRoleRequest {
  user_id: string;
  role: OrganizationRole;
}
/**
 * UpdateWSMemberRoleRequest is a request to update a user's workspace role.
 */
export interface UpdateWSMemberRoleRequest {
  user_id: string;
  role: WorkspaceRole;
}
/**
 * UpdateUserSettingsRequest is a request to update user global settings.
 */
export interface UpdateUserSettingsRequest {
  settings: UserSettings;
}
/**
 * AdminStatsRequest is a request to get admin stats.
 */
export interface AdminStatsRequest {
}
/**
 * AdminUsersRequest is a request to list all users (admin only).
 */
export interface AdminUsersRequest {
}
/**
 * AdminOrgsRequest is a request to list all organizations (admin only).
 */
export interface AdminOrgsRequest {
}

//////////
// source: response.go

/**
 * OkResponse is a simple success response.
 */
export interface OkResponse {
  ok: boolean;
}
/**
 * AuthResponse is a response containing authentication token and user info.
 * Used by login, register, and invitation acceptance endpoints.
 */
export interface AuthResponse {
  token: string;
  user?: UserResponse;
}
/**
 * ProvidersResponse is a response containing the list of configured OAuth providers.
 */
export interface ProvidersResponse {
  providers: OAuthProvider[];
}
/**
 * SessionResponse is the API representation of a session.
 */
export interface SessionResponse {
  id: string;
  device_info: string;
  ip_address: string;
  created: Time;
  last_used: Time;
  is_current: boolean;
}
/**
 * ListSessionsResponse is a response containing user's sessions.
 */
export interface ListSessionsResponse {
  sessions: SessionResponse[];
}
/**
 * LogoutResponse is a response from logout.
 */
export type LogoutResponse = OkResponse;
/**
 * RevokeSessionResponse is a response from revoking a session.
 */
export type RevokeSessionResponse = OkResponse;
/**
 * RevokeAllSessionsResponse is a response from revoking all sessions.
 */
export interface RevokeAllSessionsResponse {
  revoked_count: number /* int */;
}
/**
 * UpdateNodeResponse is a response from updating a node.
 */
export interface UpdateNodeResponse {
  id: string;
}
/**
 * DeleteNodeResponse is a response from deleting a node.
 */
export type DeleteNodeResponse = OkResponse;
/**
 * ListNodeVersionsResponse is a response containing node version history.
 */
export interface ListNodeVersionsResponse {
  history: (Commit | undefined)[];
}
/**
 * GetNodeVersionResponse is a response containing node content at a version.
 */
export interface GetNodeVersionResponse {
  content: string;
}
/**
 * ListTablesResponse is a response containing a list of tables.
 */
export interface ListTablesResponse {
  tables: TableSummary[];
}
/**
 * TableSummary is a brief representation of a table for list responses.
 */
export interface TableSummary {
  id: string;
  title: string;
  created: Time;
  modified: Time;
}
/**
 * GetTableResponse is a response containing a table.
 */
export interface GetTableResponse {
  id: string;
  title: string;
  properties: Property[];
  created: Time;
  modified: Time;
}
/**
 * CreateTableResponse is a response from creating a table.
 */
export interface CreateTableResponse {
  id: string;
}
/**
 * UpdateTableResponse is a response from updating a table.
 */
export interface UpdateTableResponse {
  id: string;
}
/**
 * DeleteTableResponse is a response from deleting a table.
 */
export type DeleteTableResponse = OkResponse;
/**
 * ListRecordsResponse is a response containing a list of records.
 */
export interface ListRecordsResponse {
  records: DataRecordResponse[];
}
/**
 * CreateRecordResponse is a response from creating a record.
 */
export interface CreateRecordResponse {
  id: string;
}
/**
 * UpdateRecordResponse is a response from updating a record.
 */
export interface UpdateRecordResponse {
  id: string;
}
/**
 * GetRecordResponse is a response containing a record.
 */
export interface GetRecordResponse {
  id: string;
  data: { [key: string]: any};
  created: Time;
  modified: Time;
}
/**
 * DeleteRecordResponse is a response from deleting a record.
 */
export type DeleteRecordResponse = OkResponse;
/**
 * ListNodesResponse is a response containing a list of nodes.
 */
export interface ListNodesResponse {
  nodes: NodeResponse[];
}
/**
 * ListNodeAssetsResponse is a response containing a list of assets.
 */
export interface ListNodeAssetsResponse {
  assets: AssetSummary[];
}
/**
 * AssetSummary is a brief representation of an asset for list responses.
 */
export interface AssetSummary {
  id: string;
  name: string;
  size: number /* int64 */;
  mime_type: string;
  created: Time;
  url: string;
}
/**
 * UploadNodeAssetResponse is a response from uploading an asset.
 */
export interface UploadNodeAssetResponse {
  id: string;
  name: string;
  size: number /* int64 */;
  mime_type: string;
}
/**
 * DeleteNodeAssetResponse is a response from deleting an asset.
 */
export type DeleteNodeAssetResponse = OkResponse;
/**
 * ServeAssetResponse wraps the binary asset data.
 */
export interface ServeAssetResponse {
  data: string;
  mime_type: string;
}
/**
 * SearchResponse is the response to a search request.
 */
export interface SearchResponse {
  results: SearchResult[];
}
/**
 * ListOrgInvitationsResponse is a response containing a list of organization invitations.
 */
export interface ListOrgInvitationsResponse {
  invitations: OrgInvitationResponse[];
}
/**
 * ListWSInvitationsResponse is a response containing a list of workspace invitations.
 */
export interface ListWSInvitationsResponse {
  invitations: WSInvitationResponse[];
}
/**
 * SwitchOrgResponse is a response from switching organization.
 */
export interface SwitchOrgResponse {
  token: string;
  user?: UserResponse;
}
/**
 * SwitchWorkspaceResponse is a response from switching workspace.
 */
export interface SwitchWorkspaceResponse {
  token: string;
  user?: UserResponse;
}
/**
 * ChangeEmailResponse is a response from changing email.
 */
export interface ChangeEmailResponse {
  ok: boolean;
  email_verified: boolean;
  message?: string;
}
/**
 * SendVerificationEmailResponse is a response from sending a verification email.
 */
export interface SendVerificationEmailResponse {
  ok: boolean;
  message?: string;
}
/**
 * LinkOAuthAccountResponse is a response from initiating OAuth linking.
 */
export interface LinkOAuthAccountResponse {
  redirect_url: string;
}
/**
 * UnlinkOAuthAccountResponse is a response from unlinking an OAuth provider.
 */
export type UnlinkOAuthAccountResponse = OkResponse;
/**
 * HealthResponse is a response from a health check.
 */
export interface HealthResponse {
  status: string;
  version: string;
}
/**
 * ListUsersResponse is a response containing a list of users.
 */
export interface ListUsersResponse {
  users: UserResponse[];
}
/**
 * UserResponse is the API representation of a user.
 */
export interface UserResponse {
  id: string;
  email: string;
  email_verified?: boolean;
  name: string;
  is_global_admin?: boolean;
  oauth_identities?: OAuthIdentity[];
  settings: UserSettings;
  created: Time;
  modified: Time;
  /**
   * Current context
   */
  organization_id?: string;
  org_role?: OrganizationRole;
  workspace_id?: string;
  workspace_name?: string;
  workspace_role?: WorkspaceRole;
  /**
   * All memberships
   */
  organizations?: OrgMembershipResponse[];
  workspaces?: WSMembershipResponse[];
}
/**
 * OrgMembershipResponse is the API representation of an organization membership.
 */
export interface OrgMembershipResponse {
  id: string;
  user_id: string;
  organization_id: string;
  organization_name?: string;
  role: OrganizationRole;
  created: Time;
}
/**
 * WSMembershipResponse is the API representation of a workspace membership.
 */
export interface WSMembershipResponse {
  id: string;
  user_id: string;
  workspace_id: string;
  workspace_name?: string;
  organization_id: string;
  role: WorkspaceRole;
  settings: WorkspaceMembershipSettings;
  created: Time;
}
/**
 * OrgInvitationResponse is the API representation of an organization invitation (excludes Token).
 */
export interface OrgInvitationResponse {
  id: string;
  email: string;
  organization_id: string;
  role: OrganizationRole;
  invited_by: string;
  expires_at: Time;
  created: Time;
}
/**
 * WSInvitationResponse is the API representation of a workspace invitation (excludes Token).
 */
export interface WSInvitationResponse {
  id: string;
  email: string;
  workspace_id: string;
  role: WorkspaceRole;
  invited_by: string;
  expires_at: Time;
  created: Time;
}
/**
 * OrganizationResponse is the API representation of an organization.
 */
export interface OrganizationResponse {
  id: string;
  name: string;
  billing_email?: string;
  quotas: OrganizationQuotas;
  settings: OrganizationSettings;
  member_count: number /* int */;
  workspace_count: number /* int */;
  created: Time;
}
/**
 * WorkspaceResponse is the API representation of a workspace.
 */
export interface WorkspaceResponse {
  id: string;
  organization_id: string;
  name: string;
  quotas: WorkspaceQuotas;
  settings: WorkspaceSettings;
  git_remote?: GitRemoteResponse;
  member_count: number /* int */;
  created: Time;
}
/**
 * GitRemoteResponse is the API representation of a git remote.
 */
export interface GitRemoteResponse {
  workspace_id: string;
  url: string;
  type: string;
  auth_type: string;
  created: Time;
  last_sync?: Time;
}
/**
 * NodeResponse is the API representation of a node.
 */
export interface NodeResponse {
  id: string;
  parent_id?: string;
  title: string;
  content?: string;
  properties?: Property[];
  created: Time;
  modified: Time;
  tags?: string[];
  favicon_url?: string;
  has_page: boolean;
  has_table: boolean;
  has_children?: boolean;
  children?: NodeResponse[];
}
/**
 * GetPageResponse is a response containing page content.
 */
export interface GetPageResponse {
  id: string;
  title: string;
  content: string;
  created: Time;
  modified: Time;
}
/**
 * CreatePageResponse is a response from creating a page.
 */
export interface CreatePageResponse {
  id: string;
}
/**
 * UpdatePageResponse is a response from updating a page.
 */
export interface UpdatePageResponse {
  id: string;
}
/**
 * DeletePageResponse is a response from deleting a page.
 */
export type DeletePageResponse = OkResponse;
/**
 * GetTableSchemaResponse is a response containing table schema.
 */
export interface GetTableSchemaResponse {
  id: string;
  title: string;
  properties: Property[];
  created: Time;
  modified: Time;
}
/**
 * CreateTableUnderParentResponse is a response from creating a table under a parent.
 */
export interface CreateTableUnderParentResponse {
  id: string;
}
/**
 * ListNodeChildrenResponse is a response containing children of a node.
 */
export interface ListNodeChildrenResponse {
  nodes: NodeResponse[];
}
/**
 * DataRecordResponse is the API representation of a data record.
 */
export interface DataRecordResponse {
  id: string;
  data: { [key: string]: any};
  created: Time;
  modified: Time;
}
/**
 * AdminStatsResponse contains server-wide statistics.
 */
export interface AdminStatsResponse {
  user_count: number /* int */;
  org_count: number /* int */;
  workspace_count: number /* int */;
}
/**
 * AdminUsersResponse contains all users in the system.
 */
export interface AdminUsersResponse {
  users: UserResponse[];
}
/**
 * AdminOrgsResponse contains all organizations in the system.
 */
export interface AdminOrgsResponse {
  organizations: OrganizationResponse[];
}
/**
 * AdminWorkspacesResponse contains all workspaces in the system.
 */
export interface AdminWorkspacesResponse {
  workspaces: WorkspaceResponse[];
}
/**
 * ListWorkspacesResponse is a response containing a list of workspaces.
 */
export interface ListWorkspacesResponse {
  workspaces: WorkspaceResponse[];
}

//////////
// source: types.go

/**
 * Time is a type alias for storage.Time to ensure it generates as 'number' in TypeScript.
 */
export type Time = number;
/**
 * PropertyType represents the type of a table property.
 */
/**
 * PropertyTypeText stores plain text values.
 */
export const PropertyTypeText = "text";
/**
 * PropertyTypeNumber stores numeric values (integer or float).
 */
export const PropertyTypeNumber = "number";
/**
 * PropertyTypeCheckbox stores boolean values.
 */
export const PropertyTypeCheckbox = "checkbox";
/**
 * PropertyTypeDate stores ISO8601 date strings.
 */
export const PropertyTypeDate = "date";
/**
 * PropertyTypeSelect stores a single selection from predefined options.
 */
export const PropertyTypeSelect = "select";
/**
 * PropertyTypeMultiSelect stores multiple selections from predefined options.
 */
export const PropertyTypeMultiSelect = "multi_select";
/**
 * PropertyTypeURL stores URLs with validation.
 */
export const PropertyTypeURL = "url";
/**
 * PropertyTypeEmail stores email addresses with validation.
 */
export const PropertyTypeEmail = "email";
/**
 * PropertyTypePhone stores phone numbers with validation.
 */
export const PropertyTypePhone = "phone";
export type PropertyType = typeof PropertyTypeText | typeof PropertyTypeNumber | typeof PropertyTypeCheckbox | typeof PropertyTypeDate | typeof PropertyTypeSelect | typeof PropertyTypeMultiSelect | typeof PropertyTypeURL | typeof PropertyTypeEmail | typeof PropertyTypePhone;
/**
 * SelectOption represents an option for select/multi_select properties.
 */
export interface SelectOption {
  id: string;
  name: string;
  color?: string;
}
/**
 * Property represents a table column with its configuration.
 */
export interface Property {
  name: string;
  type: PropertyType;
  required?: boolean;
  /**
   * Options contains the allowed values for select and multi_select properties.
   * Each option has an ID (used in storage), name (display), and optional color.
   */
  options?: SelectOption[];
}
/**
 * OrganizationRole defines the role of a user within an organization.
 */
export type OrganizationRole = string;
/**
 * OrgRoleOwner has full control including billing.
 */
export const OrgRoleOwner: OrganizationRole = "owner";
/**
 * OrgRoleAdmin can manage workspaces and members.
 */
export const OrgRoleAdmin: OrganizationRole = "admin";
/**
 * OrgRoleMember can only access granted workspaces.
 */
export const OrgRoleMember: OrganizationRole = "member";
/**
 * WorkspaceRole defines the permissions for a user within a workspace.
 */
export type WorkspaceRole = string;
/**
 * WSRoleAdmin has full workspace control.
 */
export const WSRoleAdmin: WorkspaceRole = "admin";
/**
 * WSRoleEditor can create and modify content.
 */
export const WSRoleEditor: WorkspaceRole = "editor";
/**
 * WSRoleViewer can only read content.
 */
export const WSRoleViewer: WorkspaceRole = "viewer";
/**
 * UserSettings represents global user preferences.
 */
export interface UserSettings {
  theme: string;
  language: string;
  last_active_workspaces?: string[];
}
/**
 * OAuthProvider represents a supported OAuth2 provider.
 */
/**
 * OAuthProviderGoogle represents Google OAuth.
 */
export const OAuthProviderGoogle = "google";
/**
 * OAuthProviderMicrosoft represents Microsoft OAuth.
 */
export const OAuthProviderMicrosoft = "microsoft";
/**
 * OAuthProviderGitHub represents GitHub OAuth.
 */
export const OAuthProviderGitHub = "github";
export type OAuthProvider = typeof OAuthProviderGoogle | typeof OAuthProviderMicrosoft | typeof OAuthProviderGitHub;
/**
 * OAuthIdentity represents a link between a local user and an OAuth2 provider.
 */
export interface OAuthIdentity {
  provider: OAuthProvider;
  provider_id: string;
  email: string;
  avatar_url?: string;
  last_login: Time;
}
/**
 * WorkspaceMembershipSettings represents user preferences within a specific workspace.
 */
export interface WorkspaceMembershipSettings {
  notifications: boolean;
}
/**
 * OrganizationQuotas defines limits for an organization.
 */
export interface OrganizationQuotas {
  max_workspaces: number /* int */;
  max_members_per_org: number /* int */;
  max_members_per_workspace: number /* int */;
  max_total_storage_gb: number /* int */;
}
/**
 * WorkspaceQuotas defines limits for a workspace.
 */
export interface WorkspaceQuotas {
  max_pages: number /* int */;
  max_storage_mb: number /* int */;
  max_records_per_table: number /* int */;
  max_asset_size_mb: number /* int */;
}
/**
 * UserQuota defines limits for a user.
 */
export interface UserQuota {
  max_organizations: number /* int */;
}
/**
 * OrganizationSettings represents organization-wide settings.
 */
export interface OrganizationSettings {
  default_workspace_quotas: WorkspaceQuotas;
}
/**
 * WorkspaceSettings represents workspace-wide settings.
 */
export interface WorkspaceSettings {
  allowed_domains?: string[];
  public_access: boolean;
  git_auto_push: boolean;
}
/**
 * Commit represents a commit in git history.
 */
export interface Commit {
  hash: string;
  message: string;
  timestamp: Time;
}
/**
 * SearchResult represents a single search result.
 */
export interface SearchResult {
  type: string; // "page" or "record"
  node_id: string;
  record_id?: string;
  title: string;
  snippet: string;
  score: number /* float64 */;
  matches: { [key: string]: string};
  modified: Time;
}
