// Code generated by gen-api-sdk. DO NOT EDIT.
/** ISO 8601 timestamp string (e.g. "2026-04-13T12:00:00Z"). */
export type ISOTimestamp = string & { readonly __brand: "ISOTimestamp" };


//////////
// source: types.go

export type ErrorCode =
  | "VALIDATION_FAILED"
  | "MISSING_FIELD"
  | "INVALID_FORMAT"
  | "NOT_FOUND"
  | "NODE_NOT_FOUND"
  | "TABLE_NOT_FOUND"
  | "FILE_NOT_FOUND"
  | "STORAGE_ERROR"
  | "INTERNAL_ERROR"
  | "NOT_IMPLEMENTED"
  | "CONFLICT"
  | "UNAUTHORIZED"
  | "FORBIDDEN"
  | "INVALID_PROVIDER"
  | "OAUTH_ERROR"
  | "EXPIRED"
  | "RATE_LIMIT_EXCEEDED"
  | "CANNOT_UNLINK_ONLY_AUTH"
  | "PROVIDER_ALREADY_LINKED"
  | "PROVIDER_NOT_LINKED"
  | "EMAIL_IN_USE"
  | "EMAIL_NOT_VERIFIED"
  | "QUOTA_EXCEEDED"
  | "PAYLOAD_TOO_LARGE";
/**
 * Supported values.
 */
export const ErrorCodeValidationFailed = "VALIDATION_FAILED";
export const ErrorCodeMissingField = "MISSING_FIELD";
export const ErrorCodeInvalidFormat = "INVALID_FORMAT";
export const ErrorCodeNotFound = "NOT_FOUND";
export const ErrorCodeNodeNotFound = "NODE_NOT_FOUND";
export const ErrorCodeTableNotFound = "TABLE_NOT_FOUND";
export const ErrorCodeFileNotFound = "FILE_NOT_FOUND";
export const ErrorCodeStorageError = "STORAGE_ERROR";
export const ErrorCodeInternal = "INTERNAL_ERROR";
export const ErrorCodeNotImplemented = "NOT_IMPLEMENTED";
export const ErrorCodeConflict = "CONFLICT";
export const ErrorCodeUnauthorized = "UNAUTHORIZED";
export const ErrorCodeForbidden = "FORBIDDEN";
export const ErrorCodeInvalidProvider = "INVALID_PROVIDER";
export const ErrorCodeOAuthError = "OAUTH_ERROR";
export const ErrorCodeExpired = "EXPIRED";
export const ErrorCodeRateLimitExceeded = "RATE_LIMIT_EXCEEDED";
export const ErrorCodeCannotUnlinkOnlyAuth = "CANNOT_UNLINK_ONLY_AUTH";
export const ErrorCodeProviderAlreadyLinked = "PROVIDER_ALREADY_LINKED";
export const ErrorCodeProviderNotLinked = "PROVIDER_NOT_LINKED";
export const ErrorCodeEmailInUse = "EMAIL_IN_USE";
export const ErrorCodeEmailNotVerified = "EMAIL_NOT_VERIFIED";
export const ErrorCodeQuotaExceeded = "QUOTA_EXCEEDED";
export const ErrorCodePayloadTooLarge = "PAYLOAD_TOO_LARGE";

export type EventType =
  | "node_created"
  | "node_updated"
  | "node_deleted"
  | "node_moved"
  | "records_changed"
  | "table_updated";
/**
 * Supported values.
 */
export const EventNodeCreated = "node_created";
export const EventNodeUpdated = "node_updated";
export const EventNodeDeleted = "node_deleted";
export const EventNodeMoved = "node_moved";
export const EventRecordsChanged = "records_changed";
export const EventTableUpdated = "table_updated";

export type FilterOp =
  | "equals"
  | "not_equals"
  | "contains"
  | "not_contains"
  | "starts_with"
  | "ends_with"
  | "gt"
  | "lt"
  | "gte"
  | "lte"
  | "is_empty"
  | "is_not_empty";
/**
 * Supported values.
 */
export const FilterOpEquals = "equals";
export const FilterOpNotEquals = "not_equals";
export const FilterOpContains = "contains";
export const FilterOpNotContains = "not_contains";
export const FilterOpStartsWith = "starts_with";
export const FilterOpEndsWith = "ends_with";
export const FilterOpGreaterThan = "gt";
export const FilterOpLessThan = "lt";
export const FilterOpGreaterEqual = "gte";
export const FilterOpLessEqual = "lte";
export const FilterOpIsEmpty = "is_empty";
export const FilterOpIsNotEmpty = "is_not_empty";

export type OAuthProvider =
  | "google"
  | "microsoft"
  | "github";
/**
 * Supported values.
 */
export const OAuthProviderGoogle = "google";
export const OAuthProviderMicrosoft = "microsoft";
export const OAuthProviderGitHub = "github";

export type OrganizationRole =
  | "org:owner"
  | "org:admin"
  | "org:member";
/**
 * Supported values.
 */
export const OrgRoleOwner = "org:owner";
export const OrgRoleAdmin = "org:admin";
export const OrgRoleMember = "org:member";

export type PropertyType =
  | "text"
  | "number"
  | "checkbox"
  | "date"
  | "select"
  | "multi_select"
  | "user"
  | "url"
  | "email"
  | "phone";
/**
 * Supported values.
 */
export const PropertyTypeText = "text";
export const PropertyTypeNumber = "number";
export const PropertyTypeCheckbox = "checkbox";
export const PropertyTypeDate = "date";
export const PropertyTypeSelect = "select";
export const PropertyTypeMultiSelect = "multi_select";
export const PropertyTypeUser = "user";
export const PropertyTypeURL = "url";
export const PropertyTypeEmail = "email";
export const PropertyTypePhone = "phone";

export type SortDir =
  | "asc"
  | "desc";
/**
 * Supported values.
 */
export const SortAsc = "asc";
export const SortDesc = "desc";

export type ViewType =
  | "table"
  | "board"
  | "gallery"
  | "list"
  | "calendar";
/**
 * Supported values.
 */
export const ViewTypeTable = "table";
export const ViewTypeBoard = "board";
export const ViewTypeGallery = "gallery";
export const ViewTypeList = "list";
export const ViewTypeCalendar = "calendar";

export type WorkspaceRole =
  | "ws:admin"
  | "ws:editor"
  | "ws:viewer";
/**
 * Supported values.
 */
export const WSRoleAdmin = "ws:admin";
export const WSRoleEditor = "ws:editor";
export const WSRoleViewer = "ws:viewer";

/** HealthResponse is a response from a health check. */
export interface HealthResponse {
  status: string;
  version: string;
  go_version: string;
  revision: string;
  dirty: boolean;
}

/** AdminWorkspaceDetail contains workspace details for the admin dashboard. */
export interface AdminWorkspaceDetail {
  id: string;
  org_id: string;
  name: string;
  member_count: number /* int */;
  page_count: number /* int */;
  storage_bytes: number /* int64 */;
  git_commits: number /* int */;
  created: number;
}

/** AdminOrgDetail contains organization details for the admin dashboard. */
export interface AdminOrgDetail {
  id: string;
  name: string;
  member_count: number /* int */;
  workspace_count: number /* int */;
  created: number;
  workspaces: AdminWorkspaceDetail[];
}

/** AdminRequestMetrics contains request throughput metrics. */
export interface AdminRequestMetrics {
  server_start_time: number /* float64 */;
  uptime_seconds: number /* float64 */;
  auth_count: number /* int64 */;
  write_count: number /* int64 */;
  read_auth_count: number /* int64 */;
  read_unauth_count: number /* int64 */;
}

/** AdminServerDetail contains server-wide dashboard data. */
export interface AdminServerDetail {
  user_count: number /* int */;
  org_count: number /* int */;
  workspace_count: number /* int */;
  total_storage: number /* int64 */;
  active_sessions: number /* int */;
  organizations: AdminOrgDetail[];
  request_metrics: AdminRequestMetrics;
}

/** SMTPConfigResponse contains SMTP configuration for the response (password masked). */
export interface SMTPConfigResponse {
  host: string;
  port: number /* int32 */;
  username: string;
  from: string;
}

/**
 * ResourceQuotas defines per-workspace content limits shared by server, org, and workspace layers.
 * At org and workspace layers: -1 means "inherit from parent", 0 means "disabled", positive means a limit.
 * At server layer all fields must be strictly positive.
 */
export interface ResourceQuotas {
  max_pages: number /* int */;
  max_storage_bytes: number /* int64 */;
  max_records_per_table: number /* int */;
  max_asset_size_bytes: number /* int64 */;
  max_tables_per_workspace: number /* int */;
  max_columns_per_table: number /* int */;
}

/** QuotasConfigResponse contains quota configuration for the response. */
export interface QuotasConfigResponse {
  max_pages: number /* int */;
  max_storage_bytes: number /* int64 */;
  max_records_per_table: number /* int */;
  max_asset_size_bytes: number /* int64 */;
  max_tables_per_workspace: number /* int */;
  max_columns_per_table: number /* int */;
  max_request_body_bytes: number /* int64 */;
  max_sessions_per_user: number /* int */;
  max_organizations: number /* int */;
  max_workspaces: number /* int */;
  max_users: number /* int */;
  max_total_storage_bytes: number /* int64 */;
  max_egress_bandwidth_bps: number /* int64 */;
}

/** RateLimitsConfigResponse contains rate limit configuration for the response. */
export interface RateLimitsConfigResponse {
  auth_rate_per_min: number /* int */;
  write_rate_per_min: number /* int */;
  read_auth_rate_per_min: number /* int */;
  read_unauth_rate_per_min: number /* int */;
}

/** ServerConfigResponse is a response containing server configuration. */
export interface ServerConfigResponse {
  smtp: SMTPConfigResponse;
  quotas: QuotasConfigResponse;
  rate_limits: RateLimitsConfigResponse;
}

/** SMTPConfigUpdate contains SMTP configuration fields for updates. */
export interface SMTPConfigUpdate {
  host: string;
  port: number /* int32 */;
  username: string;
  /** Empty preserves existing */
  password: string;
  from: string;
}

/** QuotasConfigUpdate contains quota configuration fields for updates. */
export interface QuotasConfigUpdate {
  max_pages: number /* int */;
  max_storage_bytes: number /* int64 */;
  max_records_per_table: number /* int */;
  max_asset_size_bytes: number /* int64 */;
  max_tables_per_workspace: number /* int */;
  max_columns_per_table: number /* int */;
  max_request_body_bytes: number /* int64 */;
  max_sessions_per_user: number /* int */;
  max_organizations: number /* int */;
  max_workspaces: number /* int */;
  max_users: number /* int */;
  max_total_storage_bytes: number /* int64 */;
  max_egress_bandwidth_bps: number /* int64 */;
}

/** RateLimitsConfigUpdate contains rate limit configuration fields for updates. */
export interface RateLimitsConfigUpdate {
  auth_rate_per_min: number /* int */;
  write_rate_per_min: number /* int */;
  read_auth_rate_per_min: number /* int */;
  read_unauth_rate_per_min: number /* int */;
}

/** UpdateServerConfigRequest is a request to update server configuration. */
export interface UpdateServerConfigRequest {
  smtp?: SMTPConfigUpdate;
  quotas?: QuotasConfigUpdate;
  rate_limits?: RateLimitsConfigUpdate;
}

/** OkResponse is a simple success response. */
export interface OkResponse {
  ok: boolean;
}

/** LoginRequest is a request to log in. */
export interface LoginRequest {
  email: string;
  password: string;
}

/** OAuthIdentity represents a link between a local user and an OAuth2 provider. */
export interface OAuthIdentity {
  provider: OAuthProvider;
  provider_id: string;
  email: string;
  avatar_url?: string;
  last_login: number;
}

/** UserSettings represents global user preferences. */
export interface UserSettings {
  theme: string;
  language: string;
  last_active_workspaces?: string[];
}

/** OrgMembershipResponse is the API representation of an organization membership. */
export interface OrgMembershipResponse {
  id: string;
  user_id: string;
  organization_id: string;
  organization_name?: string;
  role: OrganizationRole;
  created: number;
}

/** WorkspaceMembershipSettings represents user preferences within a specific workspace. */
export interface WorkspaceMembershipSettings {
  notifications: boolean;
}

/** WSMembershipResponse is the API representation of a workspace membership. */
export interface WSMembershipResponse {
  id: string;
  user_id: string;
  workspace_id: string;
  workspace_name?: string;
  organization_id: string;
  role: WorkspaceRole;
  settings: WorkspaceMembershipSettings;
  created: number;
}

/** UserResponse is the API representation of a user. */
export interface UserResponse {
  id: string;
  email: string;
  email_verified?: boolean;
  name: string;
  is_global_admin?: boolean;
  has_password?: boolean;
  oauth_identities?: OAuthIdentity[];
  settings: UserSettings;
  created: number;
  modified: number;
  /** Current context */
  organization_id?: string;
  org_role?: OrganizationRole;
  workspace_id?: string;
  workspace_name?: string;
  workspace_role?: WorkspaceRole;
  /** All memberships */
  organizations?: OrgMembershipResponse[];
  workspaces?: WSMembershipResponse[];
}

/**
 * AuthResponse is a response containing authentication token and user info.
 * Used by login, register, and invitation acceptance endpoints.
 */
export interface AuthResponse {
  token: string;
  user?: UserResponse;
}

/** RegisterRequest is a request to register a new user. */
export interface RegisterRequest {
  email: string;
  password: string;
  name: string;
}

/** AcceptInvitationRequest is a request to accept an invitation. */
export interface AcceptInvitationRequest {
  token: string;
  password: string;
  name: string;
}

/** ProvidersResponse is a response containing the list of configured OAuth providers. */
export interface ProvidersResponse {
  providers: OAuthProvider[];
}

/** SessionResponse is the API representation of a session. */
export interface SessionResponse {
  id: string;
  device_info: string;
  ip_address: string;
  country_code?: string;
  created: number;
  last_used: number;
  is_current: boolean;
}

/** ListSessionsResponse is a response containing user's sessions. */
export interface ListSessionsResponse {
  sessions: SessionResponse[];
}

/** RevokeSessionRequest is a request to revoke a specific session. */
export interface RevokeSessionRequest {
  session_id: string;
}

/** RevokeAllSessionsResponse is a response from revoking all sessions. */
export interface RevokeAllSessionsResponse {
  revoked_count: number /* int */;
}

/** ChangeEmailRequest is a request to change the user's email address. */
export interface ChangeEmailRequest {
  new_email: string;
  /** Required for security verification */
  password: string;
}

/** ChangeEmailResponse is a response from changing email. */
export interface ChangeEmailResponse {
  ok: boolean;
  email_verified: boolean;
  message?: string;
}

/** SendVerificationEmailResponse is a response from sending a verification email. */
export interface SendVerificationEmailResponse {
  ok: boolean;
  message?: string;
}

/** SwitchWorkspaceRequest is a request to switch active workspace. */
export interface SwitchWorkspaceRequest {
  ws_id: string;
}

/** SwitchWorkspaceResponse is a response from switching workspace. */
export interface SwitchWorkspaceResponse {
  token: string;
  user?: UserResponse;
}

/** UpdateUserSettingsRequest is a request to update user global settings. */
export interface UpdateUserSettingsRequest {
  settings: UserSettings;
}

/** SetPasswordRequest is a request to set or change the user's password. */
export interface SetPasswordRequest {
  /** Required if user has a password */
  current_password?: string;
  new_password: string;
}

/** LinkOAuthAccountRequest is a request to initiate linking an OAuth provider. */
export interface LinkOAuthAccountRequest {
  provider: OAuthProvider;
}

/** LinkOAuthAccountResponse is a response from initiating OAuth linking. */
export interface LinkOAuthAccountResponse {
  redirect_url: string;
}

/** UnlinkOAuthAccountRequest is a request to unlink an OAuth provider. */
export interface UnlinkOAuthAccountRequest {
  provider: OAuthProvider;
}

/** CreateOrganizationRequest is a request to create a new organization. */
export interface CreateOrganizationRequest {
  name: string;
  ensure_first?: boolean;
}

/** OrganizationQuotas defines limits for an organization. */
export interface OrganizationQuotas {
  max_pages: number /* int */;
  max_storage_bytes: number /* int64 */;
  max_records_per_table: number /* int */;
  max_asset_size_bytes: number /* int64 */;
  max_tables_per_workspace: number /* int */;
  max_columns_per_table: number /* int */;
  max_workspaces_per_org: number /* int */;
  max_members_per_org: number /* int */;
  max_members_per_workspace: number /* int */;
  max_total_storage_bytes: number /* int64 */;
}

/** OrganizationSettings represents organization-wide settings. */
export interface OrganizationSettings {
  default_workspace_quotas: ResourceQuotas;
}

/** OrganizationResponse is the API representation of an organization. */
export interface OrganizationResponse {
  id: string;
  name: string;
  billing_email?: string;
  quotas: OrganizationQuotas;
  settings: OrganizationSettings;
  member_count: number /* int */;
  workspace_count: number /* int */;
  created: number;
  /**
   * ServerResourceLimits shows the server-imposed upper bound for each resource quota.
   * The organization's resource quotas cannot exceed these server-level limits.
   */
  server_resource_limits: ResourceQuotas;
}

/** UpdateOrganizationRequest is a request to update organization details. */
export interface UpdateOrganizationRequest {
  name?: string;
}

/** UpdateOrgPreferencesRequest is a request to update organization-wide preferences. */
export interface UpdateOrgPreferencesRequest {
  settings?: OrganizationSettings;
  quotas?: OrganizationQuotas;
}

/** ListUsersResponse is a response containing a list of users. */
export interface ListUsersResponse {
  users: UserResponse[];
}

/** UpdateOrgMemberRoleRequest is a request to update a user's organization role. */
export interface UpdateOrgMemberRoleRequest {
  user_id: string;
  role: OrganizationRole;
}

/** RemoveOrgMemberRequest is a request to remove a user from an organization. */
export interface RemoveOrgMemberRequest {
  user_id: string;
}

/** OrgInvitationResponse is the API representation of an organization invitation (excludes Token). */
export interface OrgInvitationResponse {
  id: string;
  email: string;
  organization_id: string;
  role: OrganizationRole;
  invited_by: string;
  expires_at: number;
  created: number;
}

/** ListOrgInvitationsResponse is a response containing a list of organization invitations. */
export interface ListOrgInvitationsResponse {
  invitations: OrgInvitationResponse[];
}

/** CreateOrgInvitationRequest is a request to create an organization invitation. */
export interface CreateOrgInvitationRequest {
  email: string;
  role: OrganizationRole;
  /** Optional: language for invitation email (en, fr, de, es) */
  locale?: string;
}

/** CreateWorkspaceRequest is a request to create a new workspace within an organization. */
export interface CreateWorkspaceRequest {
  name: string;
  ensure_first?: boolean;
}

/** WorkspaceSettings represents workspace-wide settings. */
export interface WorkspaceSettings {
  allowed_domains?: string[];
  public_access: boolean;
  git_auto_push: boolean;
}

/** GitRemoteResponse is the API representation of a git remote. */
export interface GitRemoteResponse {
  workspace_id: string;
  url: string;
  type: string;
  auth_type: string;
  installation_id?: number /* int64 */;
  repo_owner?: string;
  repo_name?: string;
  branch?: string;
  sync_status?: string;
  last_sync_error?: string;
  created: number;
  last_sync?: number;
}

/** WorkspaceResponse is the API representation of a workspace. */
export interface WorkspaceResponse {
  id: string;
  organization_id: string;
  name: string;
  quotas: ResourceQuotas;
  settings: WorkspaceSettings;
  git_remote?: GitRemoteResponse;
  member_count: number /* int */;
  created: number;
  /**
   * ParentResourceLimits shows the effective upper bound imposed by the server and organization.
   * The workspace's resource quotas cannot exceed these combined limits.
   * Zero means unlimited at the parent level.
   */
  parent_resource_limits: ResourceQuotas;
}

/** NotionImportRequest is a request to start a Notion import into a new workspace. */
export interface NotionImportRequest {
  notion_token: string;
}

/** NotionImportResponse is a response from starting a Notion import. */
export interface NotionImportResponse {
  workspace_id: string;
  workspace_name: string;
  status: string;
}

/** NotionImportStatusResponse is a response containing import status. */
export interface NotionImportStatusResponse {
  status: string;
  progress: number /* int */;
  total: number /* int */;
  message?: string;
  pages?: number /* int */;
  databases?: number /* int */;
  records?: number /* int */;
  assets?: number /* int */;
  errors?: number /* int */;
  duration_ms?: number /* int64 */;
}

/** UpdateWorkspaceRequest is a request to update workspace details. */
export interface UpdateWorkspaceRequest {
  name?: string;
  quotas?: ResourceQuotas;
  settings?: WorkspaceSettings;
}

/** UpdateWSMembershipSettingsRequest is a request to update user preferences within a workspace. */
export interface UpdateWSMembershipSettingsRequest {
  settings: WorkspaceMembershipSettings;
}

/** UpdateGitRemoteRequest is a request to set (create or update) the git remote for a workspace. */
export interface UpdateGitRemoteRequest {
  url: string;
  /** github, gitlab, custom */
  type: string;
  /** token, ssh */
  auth_type: string;
  token?: string;
}

/** GitSyncStatusResponse is a response containing sync status. */
export interface GitSyncStatusResponse {
  sync_status: string;
  last_sync?: number;
  last_sync_error?: string;
}

/** SetupGitHubAppRemoteRequest is a request to configure a GitHub App-based remote. */
export interface SetupGitHubAppRemoteRequest {
  installation_id: number /* int64 */;
  repo_owner: string;
  repo_name: string;
  branch: string;
}

/** ListGitHubAppReposRequest is a request to list repos for a GitHub App installation. */
export interface ListGitHubAppReposRequest {
  installation_id: number /* int64 */;
}

/** GitHubAppRepoResponse represents a GitHub repository from App installation. */
export interface GitHubAppRepoResponse {
  full_name: string;
  owner: string;
  name: string;
  private: boolean;
  html_url: string;
}

/** ListGitHubAppReposResponse is a response containing GitHub App repos. */
export interface ListGitHubAppReposResponse {
  repos: GitHubAppRepoResponse[];
}

/** GitHubAppInstallationResponse represents a GitHub App installation. */
export interface GitHubAppInstallationResponse {
  id: number /* int64 */;
  account: string;
}

/** ListGitHubAppInstallationsResponse is a response containing GitHub App installations. */
export interface ListGitHubAppInstallationsResponse {
  installations: GitHubAppInstallationResponse[];
}

/** GitHubAppAvailableResponse indicates whether GitHub App is configured. */
export interface GitHubAppAvailableResponse {
  available: boolean;
}

/**
 * WorkspaceMemberResponse is a compact user representation for workspace member listings.
 * Used by the user column type to populate the picker and display names.
 */
export interface WorkspaceMemberResponse {
  id: string;
  name: string;
  email: string;
  avatar_url?: string;
}

/** ListWorkspaceMembersResponse is a response containing current workspace members. */
export interface ListWorkspaceMembersResponse {
  members: WorkspaceMemberResponse[];
}

/** ResolveUsersRequest is a request to resolve user IDs to display info. */
export interface ResolveUsersRequest {
  ids: string[];
}

/**
 * ResolvedUser represents a resolved user reference from a user-type column value.
 * IsGhost is true when the user ID is valid but the user is no longer a member.
 */
export interface ResolvedUser {
  id: string;
  name: string;
  email: string;
  avatar_url?: string;
  is_ghost?: boolean;
}

/** ResolveUsersResponse is a response containing resolved user details. */
export interface ResolveUsersResponse {
  users: ResolvedUser[];
}

/** UpdateWSMemberRoleRequest is a request to update a user's workspace role. */
export interface UpdateWSMemberRoleRequest {
  user_id: string;
  role: WorkspaceRole;
}

/** WSInvitationResponse is the API representation of a workspace invitation (excludes Token). */
export interface WSInvitationResponse {
  id: string;
  email: string;
  workspace_id: string;
  role: WorkspaceRole;
  invited_by: string;
  expires_at: number;
  created: number;
}

/** ListWSInvitationsResponse is a response containing a list of workspace invitations. */
export interface ListWSInvitationsResponse {
  invitations: WSInvitationResponse[];
}

/** CreateWSInvitationRequest is a request to create a workspace invitation. */
export interface CreateWSInvitationRequest {
  email: string;
  role: WorkspaceRole;
  /** Optional: language for invitation email (en, fr, de, es) */
  locale?: string;
}

/** GetNodeTitlesRequest is a request to get titles for multiple nodes. */
export interface GetNodeTitlesRequest {
  /** Comma-separated node IDs */
  IDs: string;
}

/** GetNodeTitlesResponse is a response containing a map of node IDs to titles. */
export interface GetNodeTitlesResponse {
  titles: { [key: string]: string};
}

/** SelectOption represents an option for select/multi_select properties. */
export interface SelectOption {
  id: string;
  name: string;
  color?: string;
}

/** Property represents a table column with its configuration. */
export interface Property {
  name: string;
  type: PropertyType;
  required?: boolean;
  /**
   * Options contains the allowed values for select and multi_select properties.
   * Each option has an ID (used in storage), name (display), and optional color.
   */
  options?: SelectOption[];
}

/** ViewColumn defines the visibility and width of a property column. */
export interface ViewColumn {
  property: string;
  width?: number /* int */;
  visible: boolean;
}

/** Filter defines a condition for filtering records. */
export interface Filter {
  property?: string;
  operator?: FilterOp;
  value?: unknown;
  and?: Filter[];
  or?: Filter[];
}

/** Sort defines the sort order for a property. */
export interface Sort {
  property: string;
  direction: SortDir;
}

/** Group defines how to group records by a property. */
export interface Group {
  property: string;
  hidden?: unknown[];
}

/** View represents a saved table view configuration. */
export interface View {
  id: string;
  name: string;
  type: ViewType;
  default?: boolean;
  columns?: ViewColumn[];
  filters?: Filter[];
  sorts?: Sort[];
  groups?: Group[];
}

/** BacklinkInfo represents a page that links to this page. */
export interface BacklinkInfo {
  node_id: string;
  title: string;
}

/** NodeResponse is the API representation of a node. */
export interface NodeResponse {
  id: string;
  parent_id?: string;
  title: string;
  content?: string;
  properties?: Property[];
  views?: View[];
  created: number;
  modified: number;
  tags?: string[];
  favicon_url?: string;
  icon?: string;
  cover?: string;
  has_page: boolean;
  has_table: boolean;
  has_children?: boolean;
  children?: NodeResponse[];
  asset_urls?: { [key: string]: string};
  backlinks?: BacklinkInfo[];
}

/** ListNodeChildrenResponse is a response containing children of a node. */
export interface ListNodeChildrenResponse {
  nodes: NodeResponse[];
}

/** MoveNodeRequest is a request to move a node to a new parent. */
export interface MoveNodeRequest {
  /** New parent node ID; 0 = root */
  new_parent_id: string;
}

/**
 * CreatePageRequest is a request to create a page under a parent node.
 * The parent ID is in the path ({id}); use "0" for root.
 */
export interface CreatePageRequest {
  title: string;
  content?: string;
  ensure_root_if_empty?: boolean;
}

/** CreatePageResponse is a response from creating a page. */
export interface CreatePageResponse {
  id: string;
}

/** GetPageResponse is a response containing page content. */
export interface GetPageResponse {
  id: string;
  title: string;
  content: string;
  created: number;
  modified: number;
}

/** UpdatePageRequest is a request to update a page's content. */
export interface UpdatePageRequest {
  title: string;
  content: string;
}

/** UpdatePageResponse is a response from updating a page. */
export interface UpdatePageResponse {
  id: string;
  /**
   * Modified is the node revision after the write. A client stores it to tell
   * its own change apart from the matching workspace SSE event.
   */
  modified: number;
}

/**
 * UpdatePageFrontmatterRequest is a request to update a page's icon and cover image.
 * Pass an empty string to clear a field.
 */
export interface UpdatePageFrontmatterRequest {
  icon: string;
  cover: string;
}

/** UpdatePageFrontmatterResponse is a response from updating a page's icon and cover. */
export interface UpdatePageFrontmatterResponse {
  id: string;
  modified: number;
}

/**
 * CreateTableRequest is a request to create a table under a parent node.
 * The parent ID is in the path ({id}); use "0" for root.
 */
export interface CreateTableRequest {
  title: string;
  properties: Property[];
}

/** CreateTableUnderParentResponse is a response from creating a table under a parent. */
export interface CreateTableUnderParentResponse {
  id: string;
}

/** GetTableSchemaResponse is a response containing table schema. */
export interface GetTableSchemaResponse {
  id: string;
  title: string;
  properties: Property[];
  views?: View[];
  created: number;
  modified: number;
}

/**
 * UpdateTableRequest is a request to update a table.
 * Now used for /nodes/{id}/table endpoint.
 */
export interface UpdateTableRequest {
  title: string;
  properties: Property[];
}

/** UpdateTableResponse is a response from updating a table. */
export interface UpdateTableResponse {
  id: string;
}

/** CreateViewRequest is a request to create a new view for a table. */
export interface CreateViewRequest {
  name: string;
  type: ViewType;
}

/** CreateViewResponse is a response from creating a view. */
export interface CreateViewResponse {
  id: string;
}

/** UpdateViewRequest is a request to update an existing view. */
export interface UpdateViewRequest {
  name?: string;
  type?: ViewType;
  columns?: ViewColumn[];
  filters?: Filter[];
  sorts?: Sort[];
  groups?: Group[];
}

/** UpdateViewResponse is a response from updating a view. */
export interface UpdateViewResponse {
  id: string;
}

/**
 * ListRecordsRequest is a request to list records in a table.
 * Now used for /nodes/{id}/table/records endpoint.
 */
export interface ListRecordsRequest {
  /** Optional: apply saved view configuration */
  ViewID: string;
  /** Optional: JSON-encoded ad-hoc filters */
  Filters: string;
  /** Optional: JSON-encoded ad-hoc sorts */
  Sorts: string;
  Offset: number /* int */;
  Limit: number /* int */;
}

/** DataRecordResponse is the API representation of a data record. */
export interface DataRecordResponse {
  id: string;
  data: { [key: string]: unknown};
  created: number;
  modified: number;
}

/** ListRecordsResponse is a response containing a list of records. */
export interface ListRecordsResponse {
  records: DataRecordResponse[];
}

/** GetRecordResponse is a response containing a record. */
export interface GetRecordResponse {
  id: string;
  data: { [key: string]: unknown};
  created: number;
  modified: number;
}

/**
 * CreateRecordRequest is a request to create a record.
 * Now used for /nodes/{id}/table/records/create endpoint.
 */
export interface CreateRecordRequest {
  data: { [key: string]: unknown};
}

/** CreateRecordResponse is a response from creating a record. */
export interface CreateRecordResponse {
  id: string;
}

/**
 * UpdateRecordRequest is a request to update a record.
 * Now used for /nodes/{id}/table/records/{rid} endpoint.
 */
export interface UpdateRecordRequest {
  data: { [key: string]: unknown};
}

/** UpdateRecordResponse is a response from updating a record. */
export interface UpdateRecordResponse {
  id: string;
}

/** ListNodeVersionsRequest is a request to list node version history. */
export interface ListNodeVersionsRequest {
  /** Max commits to return (1-1000, default 1000). */
  Limit: number /* int */;
}

/** Commit represents a commit in git history. */
export interface Commit {
  hash: string;
  message: string;
  author_name: string;
  author_email: string;
  timestamp: number;
}

/** ListNodeVersionsResponse is a response containing node version history. */
export interface ListNodeVersionsResponse {
  history: Commit[];
}

/** GetNodeVersionResponse is a response containing node content at a version. */
export interface GetNodeVersionResponse {
  content: string;
}

/** AssetSummary is a brief representation of an asset for list responses. */
export interface AssetSummary {
  id: string;
  name: string;
  size: number /* int64 */;
  mime_type: string;
  created: number;
  url: string;
}

/** ListNodeAssetsResponse is a response containing a list of assets. */
export interface ListNodeAssetsResponse {
  assets: AssetSummary[];
}

/** SearchRequest is a request to search pages and tables. */
export interface SearchRequest {
  query: string;
  limit?: number /* int */;
  match_title?: boolean;
  match_body?: boolean;
  match_fields?: boolean;
}

/** SearchResult represents a single search result. */
export interface SearchResult {
  /** "page" or "record" */
  type: string;
  node_id: string;
  record_id?: string;
  title: string;
  snippet: string;
  score: number /* float64 */;
  matches: { [key: string]: string};
  modified: number;
}

/** SearchResponse is the response to a search request. */
export interface SearchResponse {
  results: SearchResult[];
}

/** ListNotificationsRequest is a request to list notifications for the authenticated user. */
export interface ListNotificationsRequest {
  Limit: number /* int */;
  Offset: number /* int */;
  UnreadOnly: boolean;
}

/** NotificationDTO is the API representation of a notification. */
export interface NotificationDTO {
  id: string;
  type: string;
  title: string;
  body?: string;
  resource_id?: string;
  actor_id?: string;
  actor_name?: string;
  read: boolean;
  created_at: number;
}

/** ListNotificationsResponse is a response containing paginated notifications. */
export interface ListNotificationsResponse {
  notifications: NotificationDTO[];
  total: number /* int */;
  unread_count: number /* int */;
}

/** UnreadCountResponse returns the unread notification count. */
export interface UnreadCountResponse {
  count: number /* int */;
}

/** ChannelSetDTO indicates which delivery channels are enabled. */
export interface ChannelSetDTO {
  email: boolean;
  web: boolean;
}

/** NotificationPrefsDTO holds user notification preferences. */
export interface NotificationPrefsDTO {
  defaults: { [key: string]: ChannelSetDTO};
  overrides: { [key: string]: ChannelSetDTO};
}

/** UpdateNotificationPrefsRequest updates notification channel preferences. */
export interface UpdateNotificationPrefsRequest {
  overrides: { [key: string]: ChannelSetDTO};
}

/** VAPIDKeyResponse returns the server's VAPID public key. */
export interface VAPIDKeyResponse {
  public_key: string;
}

/** PushSubscribeRequest saves a push subscription. */
export interface PushSubscribeRequest {
  endpoint: string;
  p256dh: string;
  auth: string;
}

/** PushUnsubscribeRequest removes a push subscription. */
export interface PushUnsubscribeRequest {
  endpoint: string;
}

/** ErrorDetails defines the structured error information in a response. */
export interface ErrorDetails {
  code: ErrorCode;
  message: string;
}

/** ErrorResponse is the standard API error response. */
export interface ErrorResponse {
  error: ErrorDetails;
  details?: { [key: string]: unknown};
}

/** UploadNodeAssetResponse is a response from uploading an asset. */
export interface UploadNodeAssetResponse {
  id: string;
  name: string;
  size: number /* int64 */;
  mime_type: string;
  url: string;
}

/** WorkspaceEvent is the payload sent to SSE clients for real-time workspace updates. */
export interface WorkspaceEvent {
  type: EventType;
  node_id: string;
  record_id?: string;
  actor_id: string;
  modified: number;
}

